### ISSUE TITLE
Can't start gamemode on debian 9 (stretch)

### ISSUE THREAD

**Issue by pasha225** [FeralInteractive/gamemode#100]
**Describe the bug**
Can't start gamemode on debian 9, how to fix it? I run test on latest (and any others) version througth gamemoded -t

pavel@debian:~/gamemode$ ./bootstrap.sh
+ meson --prefix=/usr build -Dwith-systemd-user-unit-dir=/etc/systemd/user
The Meson build system
Version: 0.49.0
Source dir: /home/pavel/gamemode
Build dir: /home/pavel/gamemode/build
Build type: native build
Project name: gamemode
Project version: 1.3-dev
Native C compiler: cc (gcc 6.3.0 "cc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29)
Dependency libsystemd found: YES 232
Dependency threads found: YES 
Library dl found: YES
Configuring config.h using configuration

|
|Executing subproject inih 
|
|Project name: inih
|Project version: undefined
|Native C compiler: cc (gcc 6.3.0 "cc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516")
|Build targets in project: 3
|
|Subproject inih finished.
Configuring gamemoded.service using configuration
Configuring com.feralinteractive.GameMode.service using configuration
Configuring com.feralinteractive.GameMode.policy using configuration
Message: 

    Build configuration:
    ====================

    prefix:                                 /usr
    bindir:                                 /usr/bin
    datadir:                                /usr/share
    libdir:                                 /usr/lib
    libexecdir:                             /usr/libexec
    includedir:                             /usr/include
    systemd user unit directory:            /etc/systemd/user
    D-BUS service directory:                /usr/share/dbus-1/services
    PolKit Action Directory:                /usr/share/polkit-1/actions

    Options:
    ========

    daemon:                                 true
    examples:                               true
    systemd:                                true

Build targets in project: 7
Found ninja-1.7.2 at /usr/bin/ninja
+ cd build
+ ninja
[26/26] Linking target example/example.
+ set +x
Install to /usr? [Yy] y
+ sudo ninja install
[0/1] Installing files.
Installing lib/libgamemode.so.0.0.0 to /usr/lib
Installing lib/libgamemodeauto.so.0.0.0 to /usr/lib
Installing daemon/gamemoded to /usr/bin
Installing daemon/cpugovctl to /usr/libexec
Installing /home/pavel/gamemode/lib/gamemode_client.h to /usr/include
Installing /home/pavel/gamemode/data/gamemoded.8 to /usr/share/man/man8
Installing /home/pavel/gamemode/build/meson-private/gamemode.pc to /usr/lib/pkgconfig
Installing /home/pavel/gamemode/build/meson-private/gamemode-auto.pc to /usr/lib/pkgconfig
Installing /home/pavel/gamemode/build/data/gamemoded.service to /etc/systemd/user
Installing /home/pavel/gamemode/build/data/com.feralinteractive.GameMode.service to /usr/share/dbus-1/services
Installing /home/pavel/gamemode/build/data/com.feralinteractive.GameMode.policy to /usr/share/polkit-1/actions
+ systemctl --user daemon-reload

pavel@debian:~/gamemode$ gamemoded -t
Running tests...
   *basic client tests*
       *passed*
   *dual clients tests*
ERROR: failed to re-launch self with execv: No such file or directory
gamemode tests failed
ERROR: gamemode_query_status failed to return other client connected (expected 1)!
ERROR: gamemode_query_status failed to return other client connected (expected 1)!
gamemode tests failed

pavel@debian:~/gamemode$ systemctl --user enable gamemoded
Created symlink /home/pavel/.config/systemd/user/default.target.wants/gamemoded.service → /etc/systemd/user/gamemoded.service.

pavel@debian:~/gamemode$ gamemoded -t
Running tests...
   *basic client tests*
       *passed*
   *dual clients tests*
ERROR: failed to re-launch self with execv: No such file or directory
gamemode tests failed
ERROR: gamemode_query_status failed to return other client connected (expected 1)!
ERROR: gamemode_query_status failed to return other client connected (expected 1)!
gamemode tests failed

Debian 9 - popular, why this doesn't work from box?

**Comment by mdiluz** [comment]
It's possible `gamemoded -t` is failing for you, which would mean it has a bug to be fixed.

Could you give the output of `which gamemoded` as well as double check if `gamemoded -r` appears to succeed? (You'll see output in `systemctl --user status gamemoded` that makes sense.)

**Comment by pasha225** [comment]
pavel@debian:~/gamemode$ gamemoded -t
Running tests...
   *basic client tests*
       *passed*
   *dual clients tests*
ERROR: failed to re-launch self with execv: No such file or directory
gamemode tests failed
ERROR: gamemode_query_status failed to return other client connected (expected 1)!
ERROR: gamemode_query_status failed to return other client connected (expected 1)!
gamemode tests failed

pavel@debian:~/gamemode$ which gamemoded
/usr/bin/gamemoded

pavel@debian:~/gamemode$ gamemoded -r
gamemode request succeeded and is active
^CQuitting by request...

pavel@debian:~/gamemode$ systemctl --user status gamemoded
● gamemoded.service - gamemoded
   Loaded: loaded (/etc/systemd/user/gamemoded.service; disabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-02-05 21:18:51 +04; 1min 0s ago
 Main PID: 2886 (gamemoded)
   Status: "GameMode is currently deactivated."
   CGroup: /user.slice/user-1000.slice/user@1000.service/gamemoded.service
           └─2886 /usr/bin/gamemoded -l

pavel@debian:~/gamemode$ systemctl --user enable gamemoded
Created symlink /home/pavel/.config/systemd/user/default.target.wants/gamemoded.service → /etc/systemd/user/gamemoded.service.

pavel@debian:~/gamemode$ systemctl --user status gamemoded
● gamemoded.service - gamemoded
   Loaded: loaded (/etc/systemd/user/gamemoded.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-02-05 21:18:51 +04; 1min 19s ago
 Main PID: 2886 (gamemoded)
   Status: "GameMode is currently deactivated."
   CGroup: /user.slice/user-1000.slice/user@1000.service/gamemoded.service
           └─2886 /usr/bin/gamemoded -l

System is clean. 9.7 version(last).

**Comment by pasha225** [comment]
Bro, i also started it with a steam launch option. With gamemode 1.2 and last. Doesn't work. Gamemoded doesn't react at all. Written: gamemoded is inactive.

**Comment by mdiluz** [comment]
Sorry, those logs show you stopping `gamemode -r` before querying. Could you try leaving it running while checking the status?

**Comment by pasha225** [comment]
pavel@debian:~$ gamemoded -r
gamemode request succeeded and is active
^CQuitting by request...
pavel@debian:~$ gamemoded -t
Running tests...
   *basic client tests*
       *passed*
   *dual clients tests*
ERROR: failed to re-launch self with execv: No such file or directory
gamemode tests failed
ERROR: gamemode_query_status failed to return other client connected (expected 1)!
ERROR: gamemode_query_status failed to return other client connected (expected 1)!
gamemode tests failed

**Comment by mdiluz** [comment]
To clarify: could you leave `gamemoded -r` running in another terminal, and run `systemctl --user status gamemoded` in another one.

**Comment by pasha225** [comment]
pavel@debian:~$ gamemoded -r
gamemode request succeeded and is active


pavel@debian:~$ systemctl --user status gamemoded
● gamemoded.service - gamemoded
   Loaded: loaded (/etc/systemd/user/gamemoded.service; enabled
   Active: active (running) since Tue 2019-02-05 21:18:51 +04; 
 Main PID: 2886 (gamemoded)
   Status: "GameMode is now active."
   CGroup: /user.slice/user-1000.slice/user@1000.service/gamemo
           └─2886 /usr/bin/gamemoded -l
lines 1-7/7 (END)

pavel@debian:~$ gamemoded -r
gamemode request succeeded and is active
^CQuitting by request...

pavel@debian:~$ systemctl --user status gamemoded
● gamemoded.service - gamemoded
   Loaded: loaded (/etc/systemd/user/gamemoded.service; enabled
   Active: active (running) since Tue 2019-02-05 21:18:51 +04; 
 Main PID: 2886 (gamemoded)
   Status: "GameMode is currently deactivated."
   CGroup: /user.slice/user-1000.slice/user@1000.service/gamemo
           └─2886 /usr/bin/gamemoded -l

**Comment by mdiluz** [comment]
Looks like the main bits are working.

You say it doesn't work with steam? The command you pasted is missing a backslash, `$LIB` should be `\$LIB`:

```
LD_PRELOAD=$LD_PRELOAD:/usr/\$LIB/libgamemodeauto.so.0 %command%
```

Was that a bad copy/paste?

**Comment by pasha225** [comment]
Yes, all is correctly. Git deleted double.

**Comment by mdiluz** [comment]
What's the output in the terminal when you preload into a small program, like `echo` or use the direct path to the lib in `/usr/lib`?

**Comment by pasha225** [comment]
When gamemode installed from testing-buster repository - preload forks fine(1.2-6) - in future stable 10. But it's required upgrade many other packages. I want installed it from git. For correct work of system.

**Comment by pasha225** [comment]
Sorry for the wait. Can you describe a simple steps. I'm new in linux.

**Comment by pasha225** [comment]
pavel@debian:~$ LD_PRELOAD=/usr/\$LIB/libgamemodeauto.so.0 xfce4-terminal
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by pasha225** [comment]
pavel@debian:~$ LD_PRELOAD=/usr/\\$LIB/libgamemodeauto.so.0 audacious
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by pasha225** [comment]
WORKS FINE! IF first launch started with sudo. When path to sudo LD_PRELOAD=/usr/\\$LIB/libgamemodeauto.so.0 audacious. For example. THANKS! Sorry for your time.

**Comment by pasha225** [comment]
LD_PRELOAD=/usr/lib/libgamemodeauto.so.0 audacious - works.
LD_PRELOAD=/usr/\\$LIB/libgamemodeauto.so.0 audacious - doesn't.
Sorry for your time, i'm stupid guy.

**Comment by mdiluz** [comment]
No worries! it's weird that the second one doesn't. FWIW this commit https://github.com/FeralInteractive/gamemode/pull/99/commits/372a640d39d012f23a017a00a7b480b3519443f4 is in a PR now and might help in the future
