### ISSUE TITLE
Don't use -Wall and -pedantic directly

### ISSUE THREAD

**Issue by jpakkane** [FeralInteractive/gamemode#107]
The current `meson.build` adds `-Wall` and `-pedantic` unconditionally to warning flags. This is not needed, because Meson has a warning level option that for adding these automatically. Warning level 1 (the default) already has `-Wall` and the rest can be gotten by increasing the warning level.

Please consider using `default_options` in `project()` to increase the warning level instead.

**Comment by aejsmith** [comment]
Thanks for the suggestion, fixed in 11d753fa0087b6160dbeeeb635d58922e6ac83b3.
