### ISSUE TITLE
Permission denied when runnning gamemoderun

### ISSUE THREAD

**Issue by gigaSproule** [FeralInteractive/gamemode#115]
**Describe the bug**
I'm running Ubuntu 18.04 with the latest updates. I've just cloned the repo, checked out the 1.3 tag, installed all of the dependencies and then run `./bootstrap.sh`. Everything seems to be OK, except that the `gamemoderun` script does not have executable permissions. 

**To Reproduce**
1. Clone git repo
2. Checkout 1.3 tag
3. Install all the required dependencies as described in the README
4. run `./bootstrap.sh`
5. `ls -lart /usr/bin/gamemoderun`

**Expected behavior**
I would have expected the script to be executable.

**System Info (please complete the following information):**
 - OS and version: Ubuntu 18.04
 - GameMode Version: 1.3 (bc20bef283fb947d7cee23306860af04f723ae9f)

**Comment by mdiluz** [comment]
This is strange to hear, see: https://github.com/FeralInteractive/gamemode/blob/89f8c5c4b53a55077137e78a85c0448cddf4f26b/data/meson.build#L46

What version of meson do you have?

**Comment by gigaSproule** [comment]
Meson version is 0.45.1, which I installed from the Ubuntu repositories.

Output:
```
-rw-r--r-- 1 root root 300 Mar 15 21:31 /usr/bin/gamemoderun
```

**Comment by terrestrian** [comment]
I also had the same problem. You need to install latest versions of Meson and Ninja. You can easily install with pip3.

1. Delete Meson and Ninja.

`sudo apt remove meson ninja-build`

2. Use pip3 to install latest versions of Meson and Ninja.

`sudo pip3 install meson`
`sudo pip3 install ninja` 

3. Go to your gamemode directory.

`./bootstrap.sh` 

After that, you should run gamemoderun without any issues.

**Comment by gigaSproule** [comment]
To fix it, I just ran `sudo chmod +x /usr/bin/gamemoderun` and everything is fine. If there's an issue with using the bundled version from Ubuntu 18.04, then it's possibly worth adding that to the README.

**Comment by aejsmith** [comment]
Looks like the `install_mode` option was only added in Meson 0.47. I've committed 550bacf to master which should be compatible with older versions - @gigaSproule could you update to that and check that `gamemoderun` is executable after installing? You may need to do `ninja uninstall` from the build directory, then remove the build directory and run `bootstrap.sh` again, to make sure it picks up the changes.

**Comment by gigaSproule** [comment]
Uninstalled, checked out master, deleted the build directory and then re-installed it perfectly fine.

**Comment by aejsmith** [comment]
Thanks for testing, I've released 1.3.1 with the fix.

**Comment by trialism** [comment]
So 1.3.0 is not recommended, right?

**Comment by aejsmith** [comment]
Good point - I have updated the README.
