### ISSUE TITLE
Gamemode fails to run on Arch Linux

### ISSUE THREAD

**Issue by afettouhi** [FeralInteractive/gamemode#116]
**Describe the bug**
For the past month I have been unable to get gamemode to work. I am on Arch Linux with KDE 5.15.3 and a 1080 GTX card using the 418.43 drivers. I mostly use gamemode in Lutris and here I get the error

`ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

when I launch a game with gamemode option in Lutris turned on. I have tried to rebuild gamemode from the latest git master but still it fails. The systemd module is running in the background but the second it needs to launched in a game or similar it gives the above error.
Running `gamemoded -r` gives this output `gamemode request succeeded and is active` but running `gamemoded -t` gives errors

`: Loading config
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
ERROR: gamemode_query_status failed to return other client connected (expected 1)!
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Supervisor tests
:: Passed

: Client tests failed, skipping feature tests
: Tests Failed!`

Then gamemoderun option gives no output at all. So I am in a bit lost here now.

**To Reproduce**
Steps used to reproduce the behavior:
1. Launch gamemode with Lutris with gamemode option turned on
2. See above mentioned error

**Comment by XakepSDK** [comment]
`systemctl --user enable gamemoded.service`
then
`systemctl --user restart gamemoded.service`
then
`gamemoded -t`
then test lutris again

**Comment by afettouhi** [comment]
Tried that, gives the same output.

**Comment by XakepSDK** [comment]
Did you installed it from AUR? Did you run systemd commands under yourself, not root?

**Comment by afettouhi** [comment]
Yes it is installed from AUR and yes I ran the

`systemctl --user enable gamemoded.service`

as my own user not root.

**Comment by afettouhi** [comment]
Should it be at root now?

**Comment by XakepSDK** [comment]
Does `gamemoded -t` work? If it works, tell lutris to fix error.

**Comment by mdiluz** [comment]
Looks more like `libgamemodeauto.so` isn't where it should be, somehow. Do you have full output for when you ran bootstrap? Or where it was installed to?

**Comment by afettouhi** [comment]
I've given the output from 'gamemoded -t' above in my initial report.

**Comment by XakepSDK** [comment]
I had exact same error, it solved when i ran `systemctl --user restart gamemoded.service`

**Comment by afettouhi** [comment]
> I had exact same error with `gamemode -t`, it solved when i ran `systemctl --user restart gamemoded.service`

That has worked for me as well now. But if IU try to run again a second time. I get the initial output. I have also installed now the lib32-gamemode library from AUR (also git latest version). Now when I launch Lutris the error doesn't appear anymore.

**Comment by patrickRx** [comment]
I am experiencing this same issue on arch as well. I installed from the AUR. Running a game on steam returns:

ERROR: ld.so: object '/usr/lib/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

gamemoded -r and -d both seem to launch as expected. gamemoded -t returns the following:

: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
...Waiting for child to quit...
...Waiting for child to quit...
...Waiting for child to quit...
:: Passed

:: Gamemoderun and reaper thread tests
ERROR: gamemode_query_status failed to return other client connected (expected 1)!
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Supervisor tests
:: Passed

: Client tests failed, skipping feature tests
: Tests Failed!

Ive  got this working once randomly by starting, stopping, and restarting the systemd service but now I cant get it to run at all. Does anyone have ideas for how to continue trouble shooting?

**Comment by XakepSDK** [comment]
I don't have any issues. Arch, 64 and 32 bit installed.
You don't have daemon running, you must start it before `gamemoded -t` will work.
Run these commands as user, not root!
1. Use this to start daemon on login
`systemctl --user enable gamemoded.service`
2. Use this to start if not running
`systemctl --user restart gamemoded.service`
3. Use this to test if running
`gamemoded -t`

**Comment by patrickRx** [comment]
Hi, thank you for your response. I do have gamemoded running, I’ve enabled it via ‘systemctl —user enable gamemoded’ and started it as well, both via my user name, not root. I get the error I described above.

**Comment by patrickRx** [comment]
I removed the AUR version and compiled from source, works now.
