### ISSUE TITLE
Check usage of a condition variable

### ISSUE THREAD

**Issue by elfring** [FeralInteractive/gamemode#119]
[A data structure is defined for the usage of a condition variable](https://github.com/FeralInteractive/gamemode/blob/be4eeea109dc6d98ce2b0c40ce6d1b0ee5b4720b/daemon/gamemode.c#L70 "Reaper control").
I wonder about the detail that [the corresponding function “pthread_cond_wait”](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html "Wait on a condition.") is not called in this software so far.

**Comment by aejsmith** [comment]
`pthread_cond_timedwait`: https://github.com/FeralInteractive/gamemode/blob/master/daemon/gamemode.c#L618

**Comment by elfring** [comment]
Will [the waiting on conditions](https://github.com/FeralInteractive/gamemode/blob/be4eeea109dc6d98ce2b0c40ce6d1b0ee5b4720b/daemon/gamemode.c#L603 "Implementation of game_mode_context_reaper()") become relevant for more source code places?
