### ISSUE TITLE
(Question) How to use it on lutris?

### ISSUE THREAD

**Issue by ddjem87** [FeralInteractive/gamemode#134]
So i am new to linux gaming and wanted to improve my performance i saw this (gamemode) got intrested (dunno how2spell) and i am currently running my games on lutris (cracked ofc)
i am wondering how can i run gamemode or just simply install it and thats it?

**Comment by iambryan** [comment]
Chris Titus just did a video on his YouTube channel at https://youtu.be/4gyRyYfyGJw.

The quick version is install game gamemode, determine where the library is installed libgamemode.so or whatever variant of architecture and in Lutris, open preferences and add the key pair LD_PRELOAD and wherever your library is. 

Hope this helps

**Comment by ddjem87** [comment]
Thanks I already saw it, it helped tho thanks anyways!
