### ISSUE TITLE
Authentication prompt show up every time

### ISSUE THREAD

**Issue by jeffshee** [FeralInteractive/gamemode#138]
**Describe the bug**
Authentication prompt show up every time when request and exit gamemode. Super user is needed to run /usr/libexec/cpugovctl
CPU governor doesn't switch to performance/back to powersave unless authenticated. 

**To Reproduce**
Steps used to reproduce the behavior:
1. Launch gamemode with lutris, any game
2. Authentication prompt show up
3. After authentication, exit the game
4. Authentication prompt show up

**Expected behavior**
gamemode shouldn't prompt for authentication, or if it must be done, it should prompt once only, not every time

**System Info (please complete the following information):**
 - OS and version: Fedora 29
 - GameMode Version 1.3.1

**Additional context**

**Comment by priand1** [comment]
Hi Jeff,

you can try the following, maybe it helps:

- Look for a file named /etc/polkit-default-privs.standard.
- Look for the following lines in this file:

com.feralinteractive.GameMode.governor-helper no:no:yes
com.feralinteractive.GameMode.gpu-helper no:no:yes

- If these lines are missing add them to the file
- Reboot and try gamemode again

Gpuclockctl and cpugovctl should now have the required permissions to run without asking for the root password.

**Comment by jeffshee** [comment]
@priand1 Thanks!
After reading your comment, I realized that all I need is a reboot after installation for polkit to take effect. Now everything is working fine.
