### ISSUE TITLE
gamemodeauto: Could not call method on bus: No route to host

### ISSUE THREAD

**Issue by rcuyegkeng** [FeralInteractive/gamemode#14]
Hello,

When I start a game with:
`LD_PRELOAD="/usr/\$LIB/libgamemodeauto.so" ./game`

I get the message:
`gamemodeauto: Could not call method on bus: No route to host`

Is this a typical message?  Is this a sign that there was a problem with the installation?

I am running Ubuntu 16.04 LTS. bootstrap.sh was run successfully. systemctl reports that the gamemoded service is running.

Thanks!

**Comment by angrylinuxuser** [comment]
had the same issue i think i fixed it with starting deamon:
systemctl --user start gamemoded

test with systemctl --user status gamemoded if the deamon is running

if you want to start the deamon when logging in try
systemctl --user enable gamemoded

**Comment by mdiluz** [comment]
This isn't a typical message, but it doesn't have one fixed cause.

It'd be best to check if the output of this:
```
systemctl --user status gamemoded
```
To see if everything is in order. Maybe the daemon isn't running, or maybe it failed to register on the bus?

If everything is OK there, then using a tool like [d-feet](https://github.com/GNOME/d-feet) can help diagnose why the game might not reach it.

Also worth checking that you're not running steam in a flatpak/snap as that'd prevent the host-client communication.

**Comment by rcuyegkeng** [comment]
The gamemoded service seems to be running properly.
`
● gamemoded.service - gamemoded
   Loaded: loaded (/etc/systemd/user/gamemoded.service; enabled; vendor preset: 
   Active: active (running) since Wed 2018-04-11 12:28:19 EDT; 1h 7min ago
 Main PID: 31865 (gamemoded)
   CGroup: /user.slice/user-1000.slice/user@1000.service/gamemoded.service
           └─31865 /usr/bin/gamemoded -l

Apr 11 12:28:19 frankenberryjr systemd[5296]: Stopped gamemoded.
Apr 11 12:28:19 frankenberryjr systemd[5296]: Starting gamemoded...
Apr 11 12:28:19 frankenberryjr /usr/bin/gamemoded[31865]: governor is set to [po
Apr 11 12:28:19 frankenberryjr /usr/bin/gamemoded[31865]: Successfully initialis
Apr 11 12:28:19 frankenberryjr systemd[5296]: Started gamemoded.
Apr 11 13:24:30 frankenberryjr systemd[5296]: Started gamemoded.
Apr 11 13:29:31 frankenberryjr systemd[5296]: Started gamemoded.
`

I couldn't compile d-feet on my system (missing prereqs). I used dbus-monitor to filter for `com.feralinteractive.GameMode. `
`
method call time=1523467956.042176 sender=:1.273 -> destination=com.feralinteractive.GameMode serial=2 path=/com/feralinteractive/GameMode; interface=com.feralinteractive.GameMode; member=RegisterGame
   int32 5385
method call time=1523467956.052296 sender=:1.274 -> destination=com.feralinteractive.GameMode serial=2 path=/com/feralinteractive/GameMode; interface=com.feralinteractive.GameMode; member=RegisterGame
   int32 5386
method call time=1523467956.058549 sender=:1.275 -> destination=com.feralinteractive.GameMode serial=2 path=/com/feralinteractive/GameMode; interface=com.feralinteractive.GameMode; member=RegisterGame
   int32 5387
method call time=1523467956.065780 sender=:1.276 -> destination=com.feralinteractive.GameMode serial=2 path=/com/feralinteractive/GameMode; interface=com.feralinteractive.GameMode; member=RegisterGame
   int32 5387
method call time=1523467956.067738 sender=:1.277 -> destination=com.feralinteractive.GameMode serial=2 path=/com/feralinteractive/GameMode; interface=com.feralinteractive.GameMode; member=UnregisterGame
   int32 5387
method call time=1523467965.329279 sender=:1.279 -> destination=com.feralinteractive.GameMode serial=2 path=/com/feralinteractive/GameMode; interface=com.feralinteractive.GameMode; member=UnregisterGame
   int32 5385
`

So it looks like the client is passing messages to the service.  Although, I'm not sure what the service's response is.

FWIW, here's the error messages output by the client:
`
gamemodeauto: Could not call method on bus: No route to host . function: RegisterGame
gamemodeauto: Could not call method on bus: No route to host . function: RegisterGame
gamemodeauto: Could not call method on bus: No route to host . function: UnregisterGame
`

**Comment by mdiluz** [comment]
@rcuyegkeng did you ever find out a solution to this? If not, perhaps some dbus enviroment is different in your local shell?

**Comment by rcuyegkeng** [comment]
Latest build seems to be working.  I'm going to close this issue.  thanks.
