### ISSUE TITLE
ioprio and renice options do not apply to full process tree of client

### ISSUE THREAD

**Issue by mdiluz** [FeralInteractive/gamemode#140]
**Describe the bug**
This is similar to https://github.com/FeralInteractive/gamemode/issues/139

When `ioprio` is set in `gamemode.ini`, we try to use `SYS_ioprio_set` here: https://github.com/FeralInteractive/gamemode/blob/master/daemon/gamemode-ioprio.c#L86

But, based on the man page for `ioprio_set` here: http://man7.org/linux/man-pages/man2/ioprio_set.2.html

>       Two or more processes or threads can share an I/O context.  This will
>       be the case when clone(2) was called with the CLONE_IO flag.
>       However, by default, the distinct threads of a process will not share
>       the same I/O context.  This means that if you want to change the I/O
>       priority of all threads in a process, you may need to call
>       ioprio_set() on each of the threads.  The thread ID that you would
>       need for this operation is the one that is returned by gettid(2) or
>       clone(2).

This implies a default thread creation won't inherit the `ioprio` value that has been set.

Interestingly the `renice` setting sets for the whole process tree, and as noted in the above man page:

>        If no I/O scheduler has been set for a thread, then by default the
>       I/O priority will follow the CPU nice value (setpriority(2)).

Which means this issue would be masked somewhat for those using `renice`.

**To Reproduce**
Steps used to reproduce the behavior:
1. Launch multiprocess program and request gamemode
2. Check ioprio value for each thread
3. See ioprio value has not been inherited by process tree

**Expected behavior**
The `ioprio` value should be inherited for the whole tree

**System Info (please complete the following information):**
 - PopOS 19.04
 - GameMode Version 1.3.1

**Comment by mdiluz** [comment]
I've implemented tests in https://github.com/mdiluz/gamemode/commit/c082647416a98359ae0098d8a9f782e73b1b0180 to prove this issue.

**Comment by mdiluz** [comment]
#142 has the fix for this

**Comment by aejsmith** [comment]
Merged #142.
