### ISSUE TITLE
Ubuntu 19.04 libdbus1-dev

### ISSUE THREAD

**Issue by wilmervanheerde** [FeralInteractive/gamemode#153]
Could not find install `libdbus1-dev` because a dash is missing in the installation readme. Installing `libdbus-1-dev` fixed it for me

**Comment by aejsmith** [comment]
Oops, I even looked up the package name before adding it, and still managed to make a typo in the file. Fixed in 7c830bc48be286dec4e878102982bd9204ecbc09, thanks!
