### ISSUE TITLE
Ubuntu 18.04 [x86_64]  multiarch Gamemode selects x64 libs for an x86 Steam game

### ISSUE THREAD

**Issue by T-oasterO-ven** [FeralInteractive/gamemode#156]
So I compiled gamemode for Ubuntu 18.04 x86_64 I compiled the 32 bit library referencing: https://github.com/FeralInteractive/gamemode/issues/38 

My libs are located in:
/usr/lib/i386-linux-gnu
/usr/lib/x86_64-linux-gnu

However, when I launch a 32 bit game (Team Fortress 2) from Steam with the "gamemoderun %command%" launch option
it reports that it tried to load the 64 bit libraries:
`ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`

I have enabled multiarch using `dpkg --add-architecture i386`

Any help would be appreciated.

**Comment by aejsmith** [comment]
I fixed gamemoderun to automatically select the correct library path for whether the game being launched is 32- or 64-bit in commit 51606c1b1b4def30e49a28365d5961bad61103ce. I think that should fix your issue.

**Comment by tuxutku** [comment]
@aejsmith does `gamemode` replace `gamemode:,386` or do we need both of them installed (its not possible at the moment to install both packages).
Also [just linking it](https://github.com/lutris/lutris/issues/2172#issuecomment-522314043) will cause any problems on 32bit applications?
