### ISSUE TITLE
Manually enabling gamemode via DBus message

### ISSUE THREAD

**Issue by 2m** [FeralInteractive/gamemode#16]
This is a great project which replaces my custom sripts to enable performance tweaks. However I would like to toggle gamemode manually in situations where I am not playing games, but doing other resource intensive tasks, such as compiling programs.

Would it make sense to add a DBus messages to enable and disable gamemode?

**Comment by mdiluz** [comment]
Thanks, this might need a little thought but is certainly something I'd want possible at some stage.

The primary issue I see to solve is ensuring the mode will end up deactivated eventually, even if the requester fails to ask for it to end.

At the moment, simply creating a process that uses `libgamemodeauto.so` and ending it when done, will work for your purpose, even if it's a bit hacky.

**Comment by mdiluz** [comment]
After 2317bcde14c you can run `gamemoded -r` to request gamemode, however the ref-counting is still in place so you'll need to leave that instance of gamemoded running somewhere.

**Comment by 2m** [comment]
Awesome! I installed the `gamemode-git` package for Archlinux ant tested it out. Thanks for implementing this!
