### ISSUE TITLE
1.4 release 

### ISSUE THREAD

**Issue by gicmo** [FeralInteractive/gamemode#162]
I would *love* to get 1.4 into Fedora 31, because the Shell extensions also depends ([rhbz#1725103](https://bugzilla.redhat.com/show_bug.cgi?id=1725103#c6)) on it. If I read the [F31 schedule](https://fedoraproject.org/wiki/Releases/31/Schedule) correctly, 2019-07-30 is string freeze which also means the extension package should be in by that date, which can only happen if gamemode 1.4 is in rawhide before that date. It would therefore be great, if it is not too much trouble, if a 1.4 release would happen a bit before that.

**Comment by aejsmith** [comment]
Sure, we can do that. I'll try to get the release done at the weekend.

**Comment by aejsmith** [comment]
Done: https://github.com/FeralInteractive/gamemode/releases/tag/1.4

**Comment by gicmo** [comment]
I have updated the Fedora packages:
  -  [F30](https://bodhi.fedoraproject.org/updates/FEDORA-2019-277b9b91b5) update
  -  [rawhide build](https://koji.fedoraproject.org/koji/buildinfo?buildID=1316881)

I have also added integration for GameMode using the new API to GNOME usage: [MR!60](https://gitlab.gnome.org/GNOME/gnome-usage/merge_requests/60)
