### ISSUE TITLE
End command not running

### ISSUE THREAD

**Issue by tichun** [FeralInteractive/gamemode#164]
**Describe the bug**
The "end" entry in configuration file is not working.

**To Reproduce**
Steps used to reproduce the behavior:
0. Copy my config from down below
1. Use suckless dwm and slstatus
2. Run game 'Dota 2' with gamemode
3. Exit game
4. See that the end command didn't run

**Expected behavior**
In this example slstatus should run.

**System Info (please complete the following information):**
 - Ubuntu 18.04
 - gamemode version: v1.4

**Additional context**
[general]
defaultgov=powersave
renice=20
ioprio=0

[custom]
start=killall slstatus
end=slstatus

**Comment by aejsmith** [comment]
I've just checked with 1.4 and end scripts are running OK for me.

If you look at logs for gamemoded (`journalctl --user -u gamemoded -b`) do you see any messages or errors about script execution reported?

Try using a full path to slstatus in the config file?

**Comment by mdiluz** [comment]
@tichun did you resolve this? One other possibility is that `slstatus` as a command isn't returning the subshell, so `gamemoded` is likely to kill it. The log @aejsmith mentions would explain that.

**Comment by tichun** [comment]
Full path didn't help, neither do I get any logs, but I assume it's all due to my tweaked system, so I will close the issue.
