### ISSUE TITLE
The installer text to be rewritten

### ISSUE THREAD

**Issue by jimbob88** [FeralInteractive/gamemode#169]
**Is your feature request related to a problem? Please describe.**
It is half connected to an issue, the first two times I attempted to install gamemode (first from the Ubuntu official repositories and then this time from source), I failed both times (with only the `gamemoded` command being added to the system and not `gamemoderun`), yet in a last ditch attempt to fix the problem I tried three things:
First I attempted to run the command:
```
meson --reconfigure
```
Which failed with the error: `ERROR: Must specify at least one directory name.`

Secondly I attempted to run the command
```
meson setup --wipe
```
Which failed with the same error: `ERROR: Must specify at least one directory name.`

Finally I pressed `y` on the line
```
Install to /usr? [Yy]
```
I am not sure if this is just an Ubuntu user approach ( I might have this wrong and that is the correct formatting for a ninja/meson install) but when I see a capital letter I assume it means that, that item option has auto been selected like in APT:
```
Do you want to continue? [Y/n] 
```
It auto-selects Y on the enter key

**Describe the solution you'd like**
Maybe those first two commands are obvious to people who truly know what they are doing but it might be nice to have added to the end of `meson setup --wipe` and `meson --reconfigure` the build directory so they'd read `meson setup --wipe build ` and `meson --reconfigure build`.

And then perhaps `Install to /usr? [Yy]` to be rewritten as `Install to /usr? [Y/n]` or `Install to /usr? [y/N]`

**Describe alternatives you've considered**
Perhaps just leaving as it is, as I don't work with ninja and meson so I don't truly know the correct formatting of text and inputs within it but it may help with new users who are building from source because ubuntu's apt configuration of the package is broken.

Regards,
Jim

**Comment by aejsmith** [comment]
I have changed the "Install to /usr" prompt to "[y/N]" as you suggested.

I can't do anything about the prompt to run the Meson commands - that message is generated by Meson itself. You need to specify the build directory as an argument to them, which if you are using `bootstrap.sh` will be called `build`. Alternatively you could just remove the whole `build` directory and run `bootstrap.sh` again.
