### ISSUE TITLE
Gamemode failed to connect to bus in chroot

### ISSUE THREAD

**Issue by djohnson1865** [FeralInteractive/gamemode#171]
**Describe the bug**
When launching gamemoded within a gentoo-chroot I have made for all my games, the error is returned
`v1.5-dev
ERROR: Failed to connect to the bus: No such file or directory`

**To Reproduce**
Steps used to reproduce the behavior:
1. create chroot similar to [here](https://wiki.gentoo.org/wiki/Steam#Chroot)
2. run gamemoded

**Expected behavior**
gamemoded should start

**System Info (please complete the following information):**
 - Gentoo
 - v1.5-dev

**Additional context**
Dbus is mounted within the chroot session. All games work properly with my current setup, including both steam and lutris. Launching any games from lutris (with gamemode enabled in the lutris settings) breaks every game launching. Manually disabling it they run as expected.

**Comment by aejsmith** [comment]
Do you have the `DBUS_SESSION_BUS_ADDRESS` environment variable set inside the chroot to the same value that it is outside the chroot? If yes, does the path that it refers to exist inside the chroot and do you have permission to access it?

**Comment by djohnson1865** [comment]
So my system did not have `DBUS_SESSION_BUS_ADDRESS` set at all. However that was related to dbus not being compiled with user sessions enabled. After enabling that, I set the chroot to have access to the user dbus session. Now I am just getting 
```
v1.5-dev
ERROR: Failed to connect to the bus: Connection refused
```

The socket is mounted within the chroot, and the main user has rw permissions to it (identical to the main system).

**Comment by aejsmith** [comment]
I did a quick search and found that DBus connections in a chroot might fail if the chroot does not have the same machine ID as the host. Try copying `/var/lib/dbus/machine-id` from the host filesystem into the chroot?

**Comment by djohnson1865** [comment]
Okay, it looks like the issue was twofold. One issue was indeed the machine-id, so thank you for that. The other issue was merely my own ineptitude. I was setting the `DBUS_SESSION_BUS_ADDRESS` statically to `/run/user/1000/bus` instead of `unix:path=/run/user/1000/bus` in my chroot script for testing. So dbus was refusing the connection.
