### ISSUE TITLE
causes CSGO to shut down

### ISSUE THREAD

**Issue by mikasd** [FeralInteractive/gamemode#178]
**Describe the bug**
Added gamemoderun %command% to CSGO launch options after installing per the Docs.

**To Reproduce**
Steps used to reproduce the behavior:
1. Launch CSGO with normal executable including the gamemoderun %command% launch option
2. Game starts to load, then immediately closes itself

**Expected behavior**
Game to load

**System Info (please complete the following information):**
 - OS and version: PopOS 19.10
 - GameMode Version 1.4

**Comment by kochd** [comment]
Cant reproduce

**Comment by smt923** [comment]
Can't reproduce on arch 5.4.6, gamemode 1.5, gamemoderun in steam for csgo works fine for me

**Comment by rey-md** [comment]
Do you have any other launch options? I have to put "gamemoderun %command%" at the start of my launch options otherwise I can reproduce the same issue you have. I'm running arch 5.4.14 w/ gamemode 1.5.

Launch Options: gamemoderun %command% -nojoy -novid -refresh 75 +exec userconfig

**Comment by mikasd** [comment]
Updated my PopOS version and reinstalled graphics drivers and it works now. Wish I could have done a better job isolating what specifically was causing it. Thank you for the questions guys.
