### ISSUE TITLE
gamemoded's Dbus interface is overpopulated

### ISSUE THREAD

**Issue by ferdnyc** [FeralInteractive/gamemode#190]
**Describe the bug**
Exploring the session bus with D-Feet on my Fedora 31 box, I happened to notice that the `com.feralInteractive.GameMode` service is populated with standard interfaces at every path level, which is... unusual, to say the least.

Here's the GameMode service:

![image](https://user-images.githubusercontent.com/538020/73845044-cbca2580-47ef-11ea-8978-2f15d864de69.png)

And for comparison purposes, here's Nautilus:

![image](https://user-images.githubusercontent.com/538020/73845418-983bcb00-47f0-11ea-81d9-716a0528f569.png)

**Expected behavior**
It's only necessary (and is customary) to provide introspection at levels where other interfaces are implemented, so `com.feralInteractive.GameMode` would only be expected to export interfaces at  `/com/feralinteractive/GameMode` and `/com/feralinteractive/GameMode/Games`.  The rest are superfluous.

**System Info (please complete the following information):**
 - OS and version: Fedora 31 x86_64
 - GameMode Version: 1.5 (`gamemode-1.5-1.fc31.x86_64` from the official `updates` repo)

**Comment by gicmo** [comment]
This is the way `sd-bus(3)` does it; compare:

![sd-bus-logind](https://user-images.githubusercontent.com/2040/73847982-8cb7c680-4827-11ea-995f-ad4adcbe569f.png)

**Comment by ferdnyc** [comment]
@gicmo Huh, so it does! I never realized. I'll report the issue over there, then. Thanks, sorry for the noise.
