### ISSUE TITLE
Gamemode does not restore CPU governors states

### ISSUE THREAD

**Issue by Saroumane** [FeralInteractive/gamemode#197]
**Describe the bug**
The governors states prior the launch of gamemode are not restored when gamemode ends.

**To Reproduce**
Steps used to reproduce the behavior:

0. Put CPU governors in "ondemand" state :
`$ sudo cpufreqctl --governor --set=ondemand`
1. Launch gamemode with 
`$ gamemoderun stress-ng --matrix 0 -t 10s --metrics-brief`
2. After it ends, check CPU governor state : 
`$ cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor`
3. See error :
All governors are on "powersave" state.

**Expected behavior**
All CPU governors should be back to "ondemand" state at step 3.

**System Info (please complete the following information):**
 - Ubuntu 19.10
 - GameMode commit a95fa9642ecbd21a4402b8b2c5b6ad5a72c8864a (HEAD, tag: 1.5)

**Comment by afayaz-feral** [comment]
This was closed by #229
