### ISSUE TITLE
Support for hybrid graphic cards

### ISSUE THREAD

**Issue by mgerhardy** [FeralInteractive/gamemode#20]
Bumblebee, nvidia-prime and all the other options that exist

**Comment by mdiluz** [comment]
Hi @mgerhardy, to be specific here, what sort of behavior are you looking for?

Controlling optirun etc. may be something outside of the scope of a daemon, unfortunately.

It's also worth noting too that with Vulkan these issues start to go away - the game should allow you to choose which GPU is to be used.

**Comment by mgerhardy** [comment]
I'm looking for activating the main gpu automatically. To be honest I'm not sure how optirun works - but for e.g. nvidia-prime it is already enough to export an env var (`DRI_PRIME=1`) in the application context.

for example:
```
DRI_PRIME=1 glxinfo | grep OpenGL
OpenGL vendor string: nouveau
OpenGL renderer string: Gallium 0.4 on NVC1
OpenGL version string: 3.0 Mesa 9.0
OpenGL shading language version string: 1.30
```
and on the other side:
```
glxinfo | grep OpenGL 
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 9.0
OpenGL shading language version string: 1.20
```

But I'm not sure what exactly is needed for the other solutions out there.

**Comment by stephanlachnit** [comment]
I think with the new gamemoderun command this should be implemented. Currently there are 4 possible options to run an app with a secondary GPU:
DRI_PRIME=1 <app>, optirun <app>, primusrun <app>, nvidia-xrun <app>

With that in mind, it should also be added an option to set "vblank_mode=0", which disables vsync, since afaik primusrun activates this every time.

**Comment by mdiluz** [comment]
This is a cool idea actually, gamemoderun could evolve into a helper script for this kind of stuff!

**Comment by stephanlachnit** [comment]
In that case, what happens if you run gamemoderun on an app with built-in gamemode support? Because if Hybrid GPU would be implemented in gamemoderun, it would be a very nice replacement to optirun etc for Hybrid GPU user.

**Comment by mdiluz** [comment]
I think this is a fine situation - the only difference is the daemon sees the app request gamemode twice - a safe operation.

**Comment by stephanlachnit** [comment]
So is someone working on this? I would give it a shot, but I can't find where the gamemoderun code is (probably would with make, but I never used meson).

**Comment by mdiluz** [comment]
It's here: https://github.com/FeralInteractive/gamemode/blob/master/data/gamemoderun.in

It's not on my immediate list, so I'd say go for it

**Comment by stephanlachnit** [comment]
I already got the bash script working, wasn't that much work, but I would take some advice on how to get the config. I think the best option would be to add a DBUS option to gamemoded to get the config. Any suggestions?

**Comment by aejsmith** [comment]
@mdiluz Do we want to be adding major functionality to `gamemoderun`? Doing so means that games which natively support GameMode and don't need to be run through `gamemoderun` will lose out on functionality.

**Comment by mdiluz** [comment]
Yeah, I'd been mulling on it for a while - realising it'd need access to the config to make it useful kind of makes it a little bit more problematic too.

Perhaps it's simple enough for someone to write a wrapper scipt to do this for themselves?

**Comment by stephanlachnit** [comment]
I wouldn't call it a major functionality for most people. If you have a hybrid gpu, you have to use a command before starting a game anyway.
The code in gamemoderun is pretty short (see #124), the only things that's missing is the code to get the config, but that should take maybe 2 or 3 lines.
The only change missing is some option to retrieve the config options.
