### ISSUE TITLE
1.5.1 build fails without system install inih

### ISSUE THREAD

**Issue by ysblokje** [FeralInteractive/gamemode#202]
**Describe the bug**
Meson build generation fails due to typo in the inih dependency when no inih system package exists, this is with the the release archive NOT the git checkout of 1.5.1 that one actually works.

**To Reproduce**
./bootstrap.sh

**Expected behavior**
A complete build.

**System Info (please complete the following information):**
 - OS and version: Archlinux rolling
 - GameMode Version1.5.1

**Additional context**
Changing line 162 in the toplevel meson.buil from 

> fallback : ['inih', 'inih_dep']

to 

> fallback : ['inih', 'inih_dependency']

fixes the issue.

**Comment by highvoltage** [comment]
Not sure if this is related, but I tried to build in debian with the system inih packages installed and got the following:

"""
/build/gamemode-1.5.1/obj-x86_64-linux-gnu/meson-private/tmp9ot471rp/testfile.c:14:17: note: each undeclared identifier is reported only once for each function it appears in

Checking for function "pidfd_open" : NO 
Configuring build-config.h using configuration
Pkg-config binary for MachineChoice.HOST is cached.
Determining dependency 'inih' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --modversion inih` -> 1

CMake binary for MachineChoice.HOST is not cached
CMake binary missing from cross or native file, or env var undefined.
Trying a default CMake fallback at cmake
Trying CMake binary cmake for machine MachineChoice.HOST at [None]
Did not find CMake 'cmake'
Found CMake: NO
No CMake binary for machine MachineChoice.HOST not found. Giving up.
Run-time dependency inih found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency inih

meson.build:160:4: ERROR: Subproject exists but has no meson.build file
"""

**Comment by afayaz-feral** [comment]
> this is with the the release archive NOT the git checkout of 1.5.1 that one actually works.
The line in the release archive seems to be identical to the one in the git tag.

'inih_dependency' was changed to 'inih_dep' in:

https://github.com/benhoyt/inih/commit/bf2f849c77e77479bef37e6cc4131e4164938316

@stephanlachnit any thoughts?

**Comment by stephanlachnit** [comment]
> fixes the issue.

Not really, this not a fix. Your problem is that your submodule is set to the wrong repository. Easiest way is to just re-download the complete git repo, else you have to update the submodule.

**Comment by stephanlachnit** [comment]
> this is with the the release archive NOT the git checkout of 1.5.1 that one actually works.

Ahh sorry, you're right. The release archive [gamemode-1.5.1.tar.xz](https://github.com/FeralInteractive/gamemode/releases/tag/1.5.1) has the problem with the old submodule. @afayaz-feral can you re-upload it from a fresh git repo?

**Comment by afayaz-feral** [comment]
My mistake, I was checking in the auto generated "source code" archive! Recreated from a clean repo, should be all good now. @ysblokje are you able to verify on your end?

**Comment by ysblokje** [comment]
@afayaz-feral, seems ok now. I shall update the aur package to match the new release. 
I consider this closed, thanks.
