### ISSUE TITLE
Fedora 31: scaling_governor is stuck in performance after gamemode has been disabled for Intel (SB+) systems

### ISSUE THREAD

**Issue by Mershl** [FeralInteractive/gamemode#205]
**Describe the bug**
Fedora 31 does not set the scaling_governor for intel_pstate managed CPUs letting `gamemode-context.c:204` fail and unable to return to "not set" scaling_governor resulting in a system stuck in performance scaling_governor.

**To Reproduce**
Steps used to reproduce the behavior:
1. Fresh boot Fedora 31 on a intel_pstate managed system (Sandy Bridge and newer Intel system).
2. cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
> invalid argument / not set
3. gamemoderun or start gamemode enabled game
4. cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
> performance
5. quit the game
6. cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
> performance

**Expected behavior**
gamemode should return to a not set scaling_governor, as in restoring the system into the state it was before gamemode OR Fedora should set the scaling_governor to powersave on boot for Intel (Sandy Bridge and newer) systems.

**System Info (please complete the following information):**
 - OS and version: Fedora 31 Workstation
 - GameMode Version 1.5.1.fc31

**Additional information**
(1) The clock speeds and internal governor of intel_pstate were monitored and confirmed the behaviour shown in the To Reproduce steps.
(2) The background of this issue is that the intel_pstate driver is not exposing a scaling_governor and is using an internal scaling_governor instead. Setting it to powersave afterwards will not replicate the same system state as it is after a fresh boot, see [kernel.org intel_pstate activemode](https://www.kernel.org/doc/html/v4.12/admin-guide/pm/intel_pstate.html#active-mode).
(3) Setting defaultgov=powersave in gamemode.ini works as a temporary fix. Though based on the kernel doc (see (2)) powersave is not identical to the intel_pstate internal governor.

**Comment by Mershl** [comment]
I do not longer have an Intel CPU available to reproduce this issue. @truboxl Can you still reproduce it after #229?

**Comment by truboxl** [comment]
I have an IvyBridge CPU. I can't replicate the problem with gamemode v1.5-2.fc32 installed from Fedora repo without tinkering. So I think its fine now?

For testing:
```
Monitoring:
watch -n1 "paste /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor && gamemoded -s"

Dummy game:
gamemoderun /usr/bin/yes

Setting powersave (default):
sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor <<< powersave

Setting performance:
sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor <<< performance
```
I used to think I have the same problem but it turns out its another problem different from this one. Sorry about that. I will help tagging the others... @cubei @LukasNeuberger

**Comment by Mershl** [comment]
Sounds good. I'll close the issue for now. Please comment if someone can still reproduce this issue.
