### ISSUE TITLE
Error on Ubuntu 16.04 when daemon try to access glob cpufreq folders

### ISSUE THREAD

**Issue by diegodgs** [FeralInteractive/gamemode#21]
I try to start daemon and get message error " Broken glob implementation (No such file or directory)"

This message appears in file  gamemode/daemon/governors-query.c lines 49 - 54, but in my case these folders don't exist.
I have installed cpufrequtils but the folder cpufreq is in another place, see:
![image](https://user-images.githubusercontent.com/5175961/38622086-bae055ec-3d78-11e8-82b1-db97c42b740d.png)
There is beside cpu* folders instead inside cpu* folders.

**Comment by mdiluz** [comment]
This seems like a reasonable thing to fix, marked as bug.

Were you looking at making a PR, or would you like this looked into?

**Comment by mdiluz** [comment]
Alright, closing
