### ISSUE TITLE
AMDGPU Fan profile selection support

### ISSUE THREAD

**Issue by Enigmoon** [FeralInteractive/gamemode#210]
Gamemode is doing me a great favor of optimizing my system performance. Now I no longer need to type in a command to switch my CPU to Performance mode. 

My AMD rx580 also switches automatically to performance mode now. However, the fan profile remains the default option which is quite gentle and allows the temperature to reach up to 70 Celsius. I end up needing to run radeon-profile so I can activate my customized fan-curve. 

I spent so much time searching for a way to automate this process. I wonder if there is a way to configure gamemode to allow it to happen. Your advise/guidance is highly appreciated! 

Thanks!

**Comment by nanonyme** [comment]
Hm, I thought kernel was supposed to manage fans internally so that machine remains cool. I'm surprised that fan control is exposed at all.

**Comment by Enigmoon** [comment]
> Hm, I thought kernel was supposed to manage fans internally so that machine remains cool. I'm surprised that fan control is exposed at all.

@nanonyme 
From what I understand, there is a default fan-curve that increases speed as temperature goes up. However, the default fan-curve is kinda gentle and allows the temperatures to go fairly high before revving up the RPMs. 

What I did (As a work-around) is to add radeon-profile to startup applications so that it is up whenever I boot up my PC. And I made a customized fan-curve that increases RPM early on. Currently I am around 60 celsius while gaming, and this is saving me the trouble. I noticed when the temperatures go higher, I increase the odds of freezing my PC completely and end up having to force shut-it down using the power button :)

**Comment by nanonyme** [comment]
I suggest filing kernel bug in addition to this. The default fan setting is not doing its stuff if it results in freezes.

**Comment by Enigmoon** [comment]
@nanonyme It has been a while since I last ran on default fan-curves, so I will first do some gaming on the default curve and if the PC freezes, I will report a kernel bug. Thank you for your input. I will close this issue since I am not sure it will be useful to keep it open.
