### ISSUE TITLE
gamemoded sets cpu governor to powersave after exiting

### ISSUE THREAD

**Issue by jug007** [FeralInteractive/gamemode#214]
**Describe the bug**
When exiting gamemode, gamemoded sometimes sets the cpu governor to powersave, even when performance was set before entering gamemode.

**To Reproduce**
Steps used to reproduce the behavior:
1. Check cpu governor (for example with `cpupower frequency-info`)
1. Launch gamemode (with `gamemoderun application`)
2. Exit application
3. View output of 'syslog'

**Expected behavior**
Governor should be set back to performance (or not changed in the first place as that is not needed)

**System Info (please complete the following information):**
 - OS and version: Linux Mint 19.3 (Ubuntu 18.04 based)
 - GameMode Version: v1.4

**Additional context**
Governor is set to powersave on system boot. I have no idea how to change that. I change it after boot with `sudo cpupower frequency-set --governor performance`. Driver is acpi-cpufreq.

Gamemode first start:
```
Mar 28 01:01:11 motofckr9k-mint-desktop /usr/bin/gamemoded[3980]: Adding game: 5529 [/bin/bash]
Mar 28 01:01:11 motofckr9k-mint-desktop /usr/bin/gamemoded[3980]: Entering Game Mode...
Mar 28 01:01:11 motofckr9k-mint-desktop /usr/bin/gamemoded[3980]: governor was initially set to [performance]
Mar 28 01:01:11 motofckr9k-mint-desktop /usr/bin/gamemoded[3980]: Requesting update of governor policy to performance
```

Gamemode exit (first and only one)
```
Mar 28 04:04:16 motofckr9k-mint-desktop /usr/bin/gamemoded[3980]: Removing game: 9748 [/bin/bash]
Mar 28 04:04:16 motofckr9k-mint-desktop /usr/bin/gamemoded[3980]: Leaving Game Mode...
Mar 28 04:04:16 motofckr9k-mint-desktop /usr/bin/gamemoded[3980]: Requesting update of governor policy to powersave
```

**Comment by stephanlachnit** [comment]
Not a bug, this is actually intended. Check `/etc/gamemode.ini`: by default `defaultgov=powersave` is set, however if you want to have your default cpu governor to be performance, set it to `defaultgov=performance`.

**Comment by Anjune** [comment]
"Powersave" ruins performance on AMD CPUs at least. It is not a good choice for a default unless you wish to activate gamemode any time you're playing games or compiling software or encoding audio or video or, well, not having a fast CPU to begin with. I use it to get some peace and quiet, but not as a default.

It seems to me that simply commenting out the `defaultgov=` line causes Gamemode to revert the system to the governor that was in use before Gamemode kicked in -- and that, i.e. leaving such settings alone outside of Gamemode, would seem to me to be both the *expected* and the most *user-respecting* behaviour. 

Whether the user's OS defaults to "performance" or "ondemand" or "schedutil" or "powersave"... Gamemode should IMO return to *that* when it's finished. Please reconsider?

**Comment by stephanlachnit** [comment]
Good point, I agree. It's quite simple, example config has to be adjusted since that's what's going to be installed in the Debian package.
Can you submit a PR?

**Comment by Anjune** [comment]
I think I just did. :) (Not much of a dev/git-experienced person.)

**Comment by jtakeshi-nd** [comment]
This is still present on Manjaro GNOME, kernel 5.10.98-1. Also occurs when computer wakes after suspend. Using version from official Arch repositories.

**Comment by JulianGro** [comment]
@jtakeshi-nd Maybe the Arch package maintainers never updated their default config? You might want to bring the issue together with the fixing PR https://github.com/FeralInteractive/gamemode/pull/229 up to them.

**Comment by jtakeshi-nd** [comment]
The change in #229 is reflected in my .ini file. I'll try uncommenting that line and setting defaultgov=performance. It's also possible that this is from other sources.

**Comment by jtakeshi-nd** [comment]
`journalctl -b` also shows a line like:
`Mar 01 12:20:31 jonathan-desktop-manjaro pkexec[63862]: jonathan: Executing command [USER=root] [TTY=unknown] [CWD=/home/jonathan] [COMMAND=/usr/lib/gamemode/cpugovctl set powersave]`
