### ISSUE TITLE
Release public pgp key

### ISSUE THREAD

**Issue by stephanlachnit** [FeralInteractive/gamemode#215]
It's nice that we get a signature for every release, but without the public key there's no point in releasing that. In Debian we actually have an automated way to check the signature, but obviously that doesn't work without a public key.
The public key used to sign the package should be uploaded to a key server like https://keys.openpgp.org/ and linked to in the readme.

**Comment by stephanlachnit** [comment]
@afayaz-feral since there is not much going on for gamemode lately, would you consider releasing a 1.5.2 with this fixed and #207, #208 and #212 merged? Would be another nice release for Debian, maybe even gets into Ubuntu 20.04 considering the current interest of Canonical on this package.

**Comment by afayaz-feral** [comment]
This was an oversight on my part, sorry! I uploaded my public key to https://keys.openpgp.org/. You can find it [here](https://keys.openpgp.org/search?q=afayaz%40feralinteractive.com).

FWIW, I uploaded this a few weeks ago but didn't comment or close as I hadn't added the link in the readme. This also raises the question on whether we should link public keys for previous releases, as those use someone else's signatures.

**Comment by stephanlachnit** [comment]
> This also raises the question on whether we should link public keys for previous releases, as those use someone else's signatures.

If possible, that would be a nice addition, but I don't think it's strictly necessary looking forward (nobody would check it for older releases anyway I guess). If you mention in the readme since when that particular key is used, I think it's fine.

**Comment by afayaz-feral** [comment]
https://keys.openpgp.org/ is now the default keyserver in most clients. See https://keys.openpgp.org/about/news#2019-09-12-three-months-later from Sep 2019.

Therefore IMO adding a link in the readme isn't required, as the appropriate public key will be retrieved by clients.
