### ISSUE TITLE
Gamemode Error And Greyed out on Lutris

### ISSUE THREAD

**Issue by nesper8** [FeralInteractive/gamemode#216]
**Describe the bug**
Gamemode not starting

**To Reproduce**
Steps used to reproduce the behavior:
1. Launch gamemod with 'gamemoderun' on lutris Command Prefix
2. Problem in every game

**Terminal output of Black Mesa**

Running gamemoderun /home/nep/Games/Black Mesa/run.sh
Initial process has started with pid 12746
Game is considered started.
gamemodeauto: 
gamemodeauto: 
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Terminal output of VVVVVV**

Running /home/nep/.local/share/lutris/runners/wine/wine-5.5-staging-improved-amd64/bin/wine /home/nep/Games/VVVVVV/VVVVVV.exe
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Initial process has started with pid 15058
Game is considered started.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Expected behavior**
The error not happening

**System Info (please complete the following information):**
 - Linux Mint 19.3
 - GameMode 1.5.1
 - HP Laptop with Hybrid Intel HD 520 and AMD R5 M330 GPU

**Additional context**
This happens in all games in my system

**Comment by stephanlachnit** [comment]
I guess they are both 32bit applications, and you only have the 64bit libs installed. This is why the option is greyed out on Lutris afaik.

**Comment by nesper8** [comment]
So how do i build and install both the 32bit and 64bit versions?

**Comment by stephanlachnit** [comment]
Right now you have to build it from source on Debian based Distros until a `arch: any` is version is released.

**Comment by nesper8** [comment]
I've only switched to linux like in a month so how do I do that?

**Comment by stephanlachnit** [comment]
Nice to know that you switched! Sorry that I was a bit technical then.
Noramlly, you would just install the 32bit library with apt:
`apt-get install libgamemodeauto0:i386`

However, this isn't implement in the package yet so it won't work anyway.

Building it from source in both 64bit and 32bit version and installing it properly however is quite a complicated thing (tbh I'm not even sure how to properly do it), if you are new to Linux best just leave out gamemode for 32bit games. It does mainly change the cpugov, so you also just change by hand if you start a game and really need every last percent.

**Comment by stephanlachnit** [comment]
@afayaz-feral btw this can be closed now with https://github.com/lutris/lutris/commit/ac7ff9e98581b74d0a7b871f93bf1c9f802daaf2.
