### ISSUE TITLE
LD_PRELOAD cannot be preloaded

### ISSUE THREAD

**Issue by GottaSlay** [FeralInteractive/gamemode#219]
I'm trying to start a game through Lutris and this is the error code it's spamming in the console: 

`ERROR: ld.so: object 'usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

**Comment by mdiluz** [comment]
Looks like you're missing a slash before `usr` somewhere

**Comment by GottaSlay** [comment]
Oh my bad. It's here: 

`ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

There I'm trying to get it to work just by having "gamemoderun" in Lutris but it still results to the same issue.

**Comment by mdiluz** [comment]
Now it seems like your `$LIB` var has changed. Did you edit something else?

**Comment by GottaSlay** [comment]
I purged gamemode and reinstalled it by doing `sudo apt install gamemode`. Then rebooted my PC and added "gamemoderun" as a command prefix in Lutris.

Before that I was trying to have LD_PRELOAD and /usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0 as enviromental values.

Sorry for confusion. Also i'm on Ubuntu 20.04.

**Comment by GottaSlay** [comment]
I believe that I had to install gamemode 32bit as well and now my Error turned into this:

`ERROR: ld.so: object 'libgamemodeauto.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`

**Comment by rishabh900** [comment]
Why this issue is closed?? It is not solved yet.
