### ISSUE TITLE
Ability to define gamemodeauto lib dir in gamemoderun

### ISSUE THREAD

**Issue by nanonyme** [FeralInteractive/gamemode#224]
**Is your feature request related to a problem? Please describe.**
We currently ship our own gamemoderun as https://github.com/flathub/com.valvesoftware.Steam/blob/beta/resources/gamemoderun

because the way that the libdir for libgamemodeauto.so.0 is defined is not flexible enough for our sandbox layout. Specifically the usage of $LIB. Current setup is problematic as it may end up out of sync with gamemode ABI versioning.
**Describe the solution you'd like**
It would be nice to be able to define the entire library path as a single Meson variable. Current value is fine a default.
**Describe alternatives you've considered**
We could also patch gamemoderun but I'm not sure that would be much better than current workaround.

**Comment by stephanlachnit** [comment]
It should be quite easy with meson, I can do a PR.

**Comment by stephanlachnit** [comment]
Using #255 with `-Dwith-gamemoderun-lib-dir=''` should fix it.
