### ISSUE TITLE
meson `-Dwith-systemd=false` is ignored

### ISSUE THREAD

**Issue by kakra** [FeralInteractive/gamemode#226]
**Describe the bug**
Regardless of whether `--Dwith-systemd` is set false or true, it detects systemd:
```
# meson setup --buildtype plain --prefix /usr/local --wrap-mode nofallback -Dwith-systemd=false build
[...]
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libsystemd found: YES 244
[...]
```

On a non-systemd system, this leads to the following error because systemd support seems to be forced:
```
 * abi_x86_32.x86: running multilib-minimal_abi_src_configure
meson setup --buildtype plain --libdir lib --localstatedir /var/lib --prefix /usr --sysconfdir /etc --wrap-mode nodownload --cross-file /tmp/portage/games-util/gamemode-1.5.1/temp/meson.i686-pc-linux-gnu.x86 -Dwith-systemd=false -Dwith-systemd-user-unit-dir=/usr/lib/systemd/user -Dwith-examples=false -Dwith-daemon=false /tmp/portage/games-util/gamemode-1.5.1/work/gamemode-1.5.1 /tmp/portage/games-util/gamemode-1.5.1/work/gamemode-1.5.1-abi_x86_32.x86
...
...
Run-time dependency libsystemd found: NO (tried pkgconfig and cmake)
meson.build:83:0: ERROR: Dependency "libsystemd" not found, tried pkgconfig and cmake
```

See-also: https://github.com/gentoo/gentoo/pull/13158#discussion_r411892796

**Comment by stephanlachnit** [comment]
Indeed, the `meson.build` should be adjusted to
```meson
dep_systemd ​=​ ​dependency​(​'​libsystemd​'​, required: with_systemd)
```

**Comment by kakra** [comment]
Couldn't it just fallback to use non-systemd dbus then? After all, dbus activation is also possible without systemd. And it installs such a file already: /usr/share/dbus-1/services/com.feralinteractive.GameMode.service

It says `SystemdService` but that shouldn't matter at all for plain dbus without systemd.

I'm not sure why anyone would want to run a system without systemd these days, it solves a lot of long-standing problems for reliably fast booting. But Gentoo asked for it because you could install a non-systemd system (which is even default).

**Comment by stephanlachnit** [comment]
> Couldn't it just fallback to use non-systemd dbus then? After all, dbus activation is also possible without systemd. And it installs such a file already: /usr/share/dbus-1/services/com.feralinteractive.GameMode.service
> 
> It says `SystemdService` but that shouldn't matter at all for plain dbus without systemd.

The DBus implementation isn't systemd specific, but you need C bindings for DBus, and this project uses sd-bus which is made for/from systemd, it doesn't have any dependencies on systemd.
Here are some resources: [man page](https://manpages.debian.org/unstable/libsystemd-dev/sd-bus.3.en.html), [blog post](http://0pointer.net/blog/the-new-sd-bus-api-of-systemd.html)

> I'm not sure why anyone would want to run a system without systemd these days, it solves a lot of long-standing problems for reliable fast booting and proper service supervision. But Gentoo asked for it because you could install a non-systemd system (which is even default).

If it's just about the init system, installing libsystemd _should_ be no problem (depends how it's packed I guess). There's also [elogind](https://github.com/elogind/elogind) if you want to avoid anything made by systemd at all costs (it still uses some of systemd's code though), it tries to provide some of systemd's features for GNU Shepherd. As far as I see it, [it also installs sd-bus.h](https://packages.debian.org/sid/amd64/libelogind-dev/filelist), although in the `elogind` prefix, so it would require a new include flag (prepend `CFLAGS="$$CFLAGS -I/usr/include/elogind"` should do the trick).

**Comment by kakra** [comment]
I think Gentoo uses elogind for that reason, I'll discuss that with my QA contact...

**Comment by kakra** [comment]
It seems elogind also has `/usr/include/elogind/sd-bus.h`... Would this be easy to implement?

**Comment by stephanlachnit** [comment]
I can write a patch for meson. It would add a `--with-elogind` option and adds a compiler arg to change the `sd-bus.h` path in `gamemode-dbus.c`. I don't think it's possible without a new gamemode version.

**Comment by kakra** [comment]
I could simply add patches exported from git to the 1.5.1 package and just skip the patch for the package building from live git. So this issue would need to fix two problems: `--with-systemd` is ignored, and support building with elogind instead?

**Comment by stephanlachnit** [comment]
> So this issue would need to fix two problems: --with-systemd is ignored, and support building with elogind instead?

Yep, I opened #228, can you try whether it works or not? Honestly I'm not sure, at least in the Debian archive I didn't find any pkg-config entries for elogind.

**Comment by kakra** [comment]
Gentoo has it:
```
/usr/lib64/pkgconfig/libelogind.pc
```

I'll try your patch, thanks.

**Comment by kakra** [comment]
Seems still to complain with the patch applied to 1.5.1:
```
>>> Configuring source in /tmp/portage/games-util/gamemode-1.5.1/work/gamemode-1.5.1 ...
 * abi_x86_32.x86: running multilib-minimal_abi_src_configure
meson setup --buildtype plain --libdir lib --localstatedir /var/lib --prefix /usr --sysconfdir /etc --wrap-mode nodownload --pkg-config-path=/usr/share/pkgconfig --cross-file /tmp/portage/games-util/gamemode-1.5.1/temp/meson.i686-pc-linux-gnu.x86 -Dsystemd=false -Delogind=true -Dwith-systemd-user-unit-dir=/usr/lib/systemd/user -Dwith-examples=false -Dwith-daemon=false --wrap-mode forcefallback /tmp/portage/games-util/gamemode-1.5.1/work/gamemode-1.5.1 /tmp/portage/games-util/gamemode-1.5.1/work/gamemode-1.5.1-abi_x86_32.x86
...
...
...
Run-time dependency libsystemd found: NO (tried pkgconfig and cmake)

meson.build:90:4: ERROR: Dependency "libsystemd" not found, tried pkgconfig and cmake
```
