### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [FeralInteractive/gamemode#23]
I would like to point out that an identifier like “[`_CLIENT_GAMEMODE_H_`](https://github.com/FeralInteractive/gamemode/blob/69db9c2a6167c68c8e6326313d2087d03d13f442/lib/gamemode_client.h "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by mdiluz** [comment]
Thank you @elfring, now fixed in master
