### ISSUE TITLE
Gtx 1070 Powermizer

### ISSUE THREAD

**Issue by amithiel** [FeralInteractive/gamemode#231]
Hi there!
I really can't figure this out guys.
I'm using ubuntu 20.04 with a dedicated gtx 1070 max-q. nvidia driver 440.64
i edited the config file at /etc/gamemode.ini
nv_powermizer_mode=1
Started a game, and although everuthing else works (governor changes to performance), the nvidia settings remain the same.
while the game is running, i went to nvidia options/powermize and it stays on "auto mode".
i don't want to overclock my GPU, it generates enough heat already. I would just like this to automatically activate performance mode and disable it on exit.
in the config file, you mention: Requires the coolbits extension activated in nvidia-xconfig
this got me confused. is it necessary for the powermize to work? or only necessary for those who want to overclock?
in the default ubuntu 20.04, how do enable coolbits?

thanks and sorry for this novice questions

**Comment by mdiluz** [comment]
Honestly, if you don't intend to overclock, and just want the highest power setting, I'd leave this alone. NVIDIA say that the driver and GPU should power up as appropriate.

But yes, the CoolBits value needs to be changed to use any of these features, AFAIK

**Comment by amithiel** [comment]
> Honestly, if you don't intend to overclock, and just want the highest power setting, I'd leave this alone. NVIDIA say that the driver and GPU should power up as appropriate.
> 
> But yes, the CoolBits value needs to be changed to use any of these features, AFAIK

Thanks! i wont mess around with it then.
cheers
