### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [FeralInteractive/gamemode#24]
The function “[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html "Terminate a process.")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function “[sigint_handler](https://github.com/FeralInteractive/gamemode/blob/69db9c2a6167c68c8e6326313d2087d03d13f442/daemon/main.c#L73 "Update candidate")”.

**Comment by mdiluz** [comment]
Thank you @elfring, now fixed in master

**Comment by elfring** [comment]
Are the functions “game_mode_context_destroy” and “LOG_MSG” async-signal-safe?
