### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by vx-coupe** [FeralInteractive/gamemode#243]
Hi, I tried building this on Linux Mint 19.1 (which is based on Ubuntu 18.04). I got the following output -

./bootstrap.sh
+ meson --prefix=/usr build --buildtype debugoptimized -Dwith-systemd-user-unit-dir=/etc/systemd/user
The Meson build system
Version: 0.45.1
Source dir: /home/colin/gamemode
Build dir: /home/colin/gamemode/build
Build type: native build
Project name: gamemode
Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports argument -Waggregate-return: YES
Compiler for C supports argument -Wunused: YES
Compiler for C supports argument -Warray-bounds: YES
Compiler for C supports argument -Wcast-align: YES
Compiler for C supports argument -Wclobbered: YES
Compiler for C supports argument -Wempty-body: YES
Compiler for C supports argument -Wformat=2: YES
Compiler for C supports argument -Wformat-nonliteral: YES
Compiler for C supports argument -Wformat-signedness: YES
Compiler for C supports argument -Wignored-qualifiers: YES
Compiler for C supports argument -Wimplicit-function-declaration: YES
Compiler for C supports argument -Winit-self: YES
Compiler for C supports argument -Wmissing-format-attribute: YES
Compiler for C supports argument -Wmissing-include-dirs: YES
Compiler for C supports argument -Wmissing-noreturn: YES
Compiler for C supports argument -Wmissing-parameter-type: YES
Compiler for C supports argument -Wnested-externs: YES
Compiler for C supports argument -Wno-discarded-qualifiers: YES
Compiler for C supports argument -Wno-missing-field-initializers: YES
Compiler for C supports argument -Wno-suggest-attribute=format: YES
Compiler for C supports argument -Wno-unused-parameter: YES
Compiler for C supports argument -Wold-style-definition: YES
Compiler for C supports argument -Woverride-init: YES
Compiler for C supports argument -Wpointer-arith: YES
Compiler for C supports argument -Wredundant-decls: YES
Compiler for C supports argument -Wreturn-type: YES
Compiler for C supports argument -Wshadow: YES
Compiler for C supports argument -Wsign-compare: YES
Compiler for C supports argument -Wstrict-aliasing=3: YES
Compiler for C supports argument -Wstrict-prototypes: YES
Compiler for C supports argument -Wstringop-overflow: YES
Compiler for C supports argument -Wstringop-truncation: NO
Compiler for C supports argument -Wtype-limits: YES
Compiler for C supports argument -Wundef: YES
Compiler for C supports argument -Wuninitialized: YES
Compiler for C supports argument -Wunused-but-set-variable: YES
Compiler for C supports argument -Wwrite-strings: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libsystemd found: YES 237
Native dependency dbus-1 found: YES 1.12.2
Dependency threads found: YES
Library dl found: YES
Checking for function "pidfd_open": NO
Configuring build-config.h using configuration
Also couldn't find a fallback subproject in subprojects/inih for the dependency inih 
Reason: 'directory'

Dependency inih not found but it is available in a sub-subproject.
To use it in the current project, promote it by going in the project source
root and issuing the following command.

meson wrap promote subprojects/inih.wrap

meson.build:161:4: ERROR: Native dependency 'inih' not found

A full log can be found at /home/colin/gamemode/build/meson-logs/meson-log.txt

I then ran the suggested command which didn't work. What do I have to do to build this?
Thanks, Colin

meson wrap promote ~/gamemode/subprojects/inih.wrap
Subproject inih.wrap not found in directory tree.

**Comment by stephanlachnit** [comment]
I suppose your Meson version is out of date. To fix this you can either download a newer Meson version or download prebuild binaries. You can take them from Debian for example:
- https://packages.debian.org/bullseye/amd64/gamemode/download
- https://packages.debian.org/bullseye/amd64/gamemode-daemon/download
- https://packages.debian.org/bullseye/amd64/libgamemode0/download
- https://packages.debian.org/bullseye/amd64/libgamemodeauto0/download

For 32bit support:
- https://packages.debian.org/bullseye/i386/libgamemode0/download
- https://packages.debian.org/bullseye/i386/libgamemodeauto0/download

Download the debs and install them with
```sh
sudo apt install -f path/to/gamemode.deb path/to/gamemode-daemon.deb ...
```

It's important to do it one command, else you get missing dependencies.

**Comment by vx-coupe** [comment]
Hi, thanks for the reply. I tried the binaries but that didn't work. Then I tried a later version of Meson, I could finally build it but it seemed to have a negative impact. The reason I got gamemode was when running the latest version of FS-UAE (Amiga emulator) it displays the message "CPU scaling governor is Ondemand not Performance, emulator performance may suffer". When I searched for this I found gamemode. When I start the emulator with gamemode it takes at least 10 seconds to start emulating an Amiga. When I uninstalled it, it starts almost instantlty. Also it still displayed the meesage with gamemode running. I couldn't find any information on the FS-UAE about what was needed to remove the message so I assumed  that gamemode would fix it. Then I  saw that to run a game use the prefix gamemoderun. When I did this it failed to run with the following. So I don't know what to think now.

gamemoderun fs-uae-launcher %f
GameMode ERROR: D-Bus error: Could not call method 'RegisterGame' on 'com.feralinteractive.GameMode': Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
gamemodeauto: D-Bus error: Could not call method 'RegisterGame' on 'com.feralinteractive.GameMode': Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

When I pressed Ctrl C

Traceback (most recent call last):
  File "/usr/bin/fs-uae-launcher", line 121, in <module>
    main()
  File "/usr/bin/fs-uae-launcher", line 118, in main
    launcher.apps.main()
  File "/usr/share/fs-uae-launcher/launcher/apps/__init__.py", line 130, in main
    from fsbc.init import initialize_application
  File "/usr/share/fs-uae-launcher/fsbc/init.py", line 7, in <module>
    from fsbc.application import Application
  File "/usr/share/fs-uae-launcher/fsbc/application.py", line 8, in <module>
    from fsbc.paths import Paths
  File "/usr/share/fs-uae-launcher/fsbc/paths.py", line 7, in <module>
    from fsbc.system import windows, macosx
  File "/usr/share/fs-uae-launcher/fsbc/system.py", line 18, in <module>
    class System:
  File "/usr/share/fs-uae-launcher/fsbc/system.py", line 25, in System
    if _platform.machine().lower() in [
  File "/usr/lib/python3.6/platform.py", line 1128, in machine
    return uname().machine
  File "/usr/lib/python3.6/platform.py", line 1057, in uname
    processor = _syscmd_uname('-p', '')
  File "/usr/lib/python3.6/platform.py", line 814, in _syscmd_uname
    output = f.read().strip()

**Comment by vx-coupe** [comment]
I figured out how to temporarily set the CPU governor and now I don't get the message in FS_UAE so that's good. I used the following command  -

sudo cpufreq-set -g performance

I assume gamemode is just not designed for some programs. I will test it out on some actual games, although I don't know how to tell if it makes any difference, display the frame rate somehow?

**Comment by stephanlachnit** [comment]
> I assume gamemode is just not designed for some programs.

I highly doubt that, gamemode does nothing to the game at all, except preloading a pretty tiny lib. To me it looks more like gamemode isn't properly installed on your system.

**Comment by GitGuy2Point0** [comment]
Had the same meson version (0.45.1) and the build crashed due to :

lib/meson.build:28:0: ERROR: Unknown function "both_libraries".

This was remedied  by upgrading meson using the command:

pip3 install meson

At this point I cannot attest to how the program functions, but the build and installation were successful after the meson upgrade.

**Comment by stephanlachnit** [comment]
> Had the same meson version (0.45.1) and the build crashed due to :
> 
> `meson.build:28:0: ERROR: Unknown function "both_libraries".``

This (`both_libraries`) was introduced after that issue report. But yes, Meson >=0.46 is required for that, which is not featured in Ubuntu 18.04 LTS.

**Comment by redapemusic35** [comment]
I was having the same error as @vx-coupe. I followed the instructions on this [page](https://mesonbuild.com/Getting-meson.html) and was able to install meson =< 56. After this I was able to successfully install gamemode. Here are the relevant bits which worked for me

```
Installing Meson with pip

Meson is available in the Python Package Index and can be installed with sudo pip3 install meson which requires root and will install it system-wide.
```

**Comment by vx-coupe** [comment]
I did fix my problem also by installing a newer version of Meson. I just forgot to close this issue! In the end I never really used gamemode as my main aim was to stop the annoying message from FS-UAE. I discovered a more convenient method than the terminal command, by installing indicator-cpufreq from the package manager, it provides a pop-up menu on the panel where you can select the CPU Frequency.
