### ISSUE TITLE
Use `gamemoded --test` in the CI

### ISSUE THREAD

**Issue by stephanlachnit** [FeralInteractive/gamemode#246]
If it's there it should be used, right?
It currently fails (at least for me), see also #176.

**Comment by mdiluz** [comment]
Fwiw I couldn't run the binary in Travis before because the distro in there didn't have a system user bus set up. Wonder if its been updated now so we can.

**Comment by stephanlachnit** [comment]
It's possible to start one with `dbus-run-session -- <program>`, like with `gamemode-simulate-game` in travis rn.

**Comment by stephanlachnit** [comment]
See #256.
