### ISSUE TITLE
Doesnt work under steam

### ISSUE THREAD

**Issue by ajgp** [FeralInteractive/gamemode#25]
I havent been able to get gamemode to work under steam.

I added the LD_Preload arguement to the games steam launch options, but when executed my CPU governor doesnt change to performance.  Running steam from the command line I see that when it attempts to load up the library it gives a cannot access warning then ignores.

If I lauch the game directly from the games executable with the LD_preload arguement then gamemode appears to work perfectly normally.

Gamemode was installed manually on my machine and installed via the bootstrap.sh process.  I tried via the AUR package but with that the gamemoded service never started and errored when manually attempting.

O/S:  Manjaro  4.15 Kernel

**Comment by mdiluz** [comment]
If you have the exact error output given, and the steam launch option argument entry, then we might be able to see what's going on.

Thanks

**Comment by ajgp** [comment]
Apologies should have included the error with the first comment.

ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

I added the "LD_PRELOAD=$LD_PRELOAD:/usr/\$LIB/libgamemodeauto.so %command%" string to the games Steam Launch command.

**Comment by mdiluz** [comment]
Could you try this instead? The backslash in `\$LIB` is important here, and might be the issue

```
LD_PRELOAD=$LD_PRELOAD:/usr/\$LIB/libgamemodeauto.so %command%
```

**Comment by ajgp** [comment]
Just checked the launch option does include the \$LIB in the preload string   I copied and pasted the above into my comment from the readme.md as I'm on a different machine so not sure why the \ was dropped in my comment.

**Comment by mdiluz** [comment]
No worries!

Does, this work on the command line?

```
LD_PRELOAD="$LD_PRELOAD:/usr/\$LIB/libgamemodeauto.so" glxgears
```

Replace glxgears with any other executable binary, if needed.

I assume not, in which case where did `libgamemodeauto.so` end up installed for you?

**Comment by ajgp** [comment]
Both

'LD_PRELOAD=/usr/\$LIB/libgamemodeauto.so ./stellaris'  and 'LD_PRELOAD="$LD_PRELOAD:/usr/\$LIB/libgamemodeauto.so" ./stellaris'

result in the same error output as in the case of the steam launch option.

'libgamemodeauto.so' is installed into '/usr/lib'

**Comment by mdiluz** [comment]
So `$LIB` should expand out to lib or lib64, as noted [here](http://man7.org/linux/man-pages/man8/ld.so.8.html). On Arch this works because `/usr/lib64` is a symlink to `/usr/lib`, I'm guessing there's no similar link on your Manjaro installation?

**Comment by lordheavy** [comment]
You have this error because stellaris is a 32-bit game, so to avoid "wrong ELF class" yopu need to build a 32-bit version of libgamemode, see https://aur.archlinux.org/packages/lib32-gamemode/

**Comment by pschichtel** [comment]
I can confirm this working with the mentioned AUR package.

**Comment by ajgp** [comment]
Ok I feel like an idiot right now;  should have checked that!

I now have both  `gamemode` and `lib32-gamemode` installed from AUR  and it seems to be functioning
