### ISSUE TITLE
Strange Graphic bug in native Linux Games

### ISSUE THREAD

**Issue by Toadfield** [FeralInteractive/gamemode#268]
After installing gamemode and rebooring Linux,I wanted to play Duke Nukem with EDuke32,while playing I encountert a annoying bug that looks like a very old tv "renewing" effect,I can't describe it properly,it just looks like the image renews all the time.
It can't have anything to do with Duke Nukem,because this happens in other games too.

**Comment by mdiluz** [comment]
Gamemode shouldn't really have any effect on graphics, I would assume the reboot also updated your drivers, kernel, or something else.

You'll probably want to report this somewhere else. When you do though you'll want to take some screenshots or video.

**Comment by Toadfield** [comment]
sorry,the problem wasn't because of gamemode,it was because I didn't lock the fps in EDuke32 and then had screen tearing.
