### ISSUE TITLE
Question:How can I enable gamemode for MineCraft:Java Edition?

### ISSUE THREAD

**Issue by Valleriite** [FeralInteractive/gamemode#270]
Hey there!
I know this may be a duplicate of #267 ,but as far as I can see the issue wasn't addressed,
I wanted to enable gamemode for MineCraft:Java Edition,
as #267 says it isn't clear how to do so,
the readme says use ATlauncher but the instructions aren't clear + I don't want to use third party launchers,
So is there a way to enable it for the official launcher, or at least enable it for all java programmes?
Have a nice day!

**Comment by mrzban** [comment]
GameMode integration with official non-java launcher: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/3044285-fps-booster-for-java-edition-up-to-two-times-more
