### ISSUE TITLE
Using gamemoderun and GAMEMODERUNEXEC with mangohud

### ISSUE THREAD

**Issue by sgleizes** [FeralInteractive/gamemode#277]
**Describe the bug**
Currently, if I add `mangohud` to GAMEMODERUNEXEC, it doesn't work because the `LD_PRELOAD` set by mangohud gets overridden by gamemoderun. It does work by using `gamemoderun mangohud <game>` though.

This is a really minor bug, but I would like to keep `gamemoderun` as the only entrypoint for all my games, and it seems to make sense for gamemoderun to allow other programs to update `LD_PRELOAD`.

**To Reproduce**
Steps used to reproduce the behavior:
1. Run `GAMEMODERUNEXEC=mangohud gamemoderun <game>`
2. MangoHud is not loaded.

**Expected behavior**
gamemoderun should allow command prefixes that also modify LD_PRELOAD.

**Proposed solution**
Update the last line of `gamemoderun` from:
`exec $GAMEMODERUNEXEC env LD_PRELOAD="${LD_PRELOAD}" "$@"`
to:
`exec env LD_PRELOAD="${LD_PRELOAD}" $GAMEMODERUNEXEC "$@"`

**Comment by stephanlachnit** [comment]
Instead of using `mangohud` as gamemoderunexec, you can add `env MANGOHUD=1` or similar.

Tbh, now that `optirun` is kinda useless, it might be a good idea to allow setting any environment variables in `gamemoderun` instead of executing a command.

**Comment by sgleizes** [comment]
The `MANGOHUD` environment variable only works for vulkan games, not for opengl games as described [here](https://github.com/flightlessmango/MangoHud#normal-usage). Tested and confirmed.

**Comment by afayaz-feral** [comment]
Definitely looks useful to be able to override `LD_PRELOAD`, will merge #278.

**Comment by stephanlachnit** [comment]
When I implemented this, we didn't do that on purpose - I don't really remember why though.

Also, this only works because `mangohud` extends `LD_PRELOAD` instead of overwriting it (what we do), it's by no means a guarante that this works with any launcher / script.

**Comment by afayaz-feral** [comment]
If you're intentionally overriding `LD_PRELOAD`, I consider that "You know what you're doing" territory.

If a third party utility does something that causes conflicts, we can document that and possibly work with them to sort it out.
