### ISSUE TITLE
`ninja install` installs a static library (libgamemodeauto.a) - how to resolve?

### ISSUE THREAD

**Issue by kakra** [FeralInteractive/gamemode#287]
I don't think that building/installation of `/usr/lib/libgamemodeauto.a` is needed, or is it for game developers to statically link gamemode into their binary? What is the proposed solution?

Gentoo QA complains about this.

See-also: https://bugs.gentoo.org/745096

**Comment by stephanlachnit** [comment]
Package inih. Or set the `default_libraries` Meson variable for inih to shared.

**Comment by kakra** [comment]
That's not about inih, inih is packaged separately already now in Gentoo, linked dynamically.

**Comment by stephanlachnit** [comment]
Ahhh ups sry misread. Yeah it's for game devs, just like the header and pkgconfig files.

**Comment by kakra** [comment]
Is there a way to make installing that .a file opt-in or opt-out? Because Gentoo QA requires that static libs are only installed when explicitly opting in through a packaging flag (useflag). Of course, I could just `rm` the file before packaging it but if it would not be built in the first place unless requested, that's probably a cleaner solution.

Also, Gentoo calls this flag `static-libs` which doesn't quite serve the purpose of this libs, IMHO, as it is meant for development. So I'd rather have it as an optional thing and make add a `devel` useflag and maybe also remove pkgconfig installation maybe? Because otherwise, the devel toolchain of gamemode would be incomplete. So, either go with everything or none, I guess.

**Comment by stephanlachnit** [comment]
Hm no that isn't really possible in an easy way (one could implement a rather ugly if else statement, but IMHO the static lib certainly belongs to the development files). However we could add an option to not install any development files (but this is rather unusual, in Debian, Fefora etc all dev files are installed by default and put in a separate package).

**Comment by kakra** [comment]
I'll discuss with the Gentoo devs first what the preferred approach would be, based on that I either remove just that file from packaging (unless opted in), or I'll suggest to add the option to not install devel files at all.

**Comment by stephanlachnit** [comment]
> However, discarding static libs from install just for being static libs seems a bit like a sledge hammer method to me.

Usually I agree here, especially for system libs. However, most game development can't rely on system libs for compatibility reasons.
