### ISSUE TITLE
Nice value not applying to games

### ISSUE THREAD

**Issue by pongo1231** [FeralInteractive/gamemode#291]
**Describe the bug**
The `renice` value set in gamemode.ini doesn't apply to any games which run gamemode by either adding a `gamemoderun` before the actual command or automatically by running a game which natively supports gamemode. The gamemode.ini is definitely being detected and seems to apply any other options without any issue.

**To Reproduce**
Steps used to reproduce the behavior:
1. Create a gamemode.ini with the default template in any of the mentioned paths
2. Change the value of `renice` to any value above 0 (4 in my case)
3. Start up any game with gamemode
4. Use a tool like `htop` to see the nice value of that game

**Expected behavior**
The game should have the correct nice value set (-4 in my case).

**System Info (please complete the following information):**
 - OS and version: Arch Linux on the zen kernel (5.8.13-zen1-2-zen)
 - GameMode Version: v1.6-dev

**Additional context**
I have [ananicy](https://github.com/Nefelim4ag/Ananicy) installed which also messes with the nice values of processes, however the issue still occurs after stopping ananicy and trying again.

Output of `gamemoded -t`:
```
: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Passed

:: Supervisor tests
:: Passed

:: Feature tests
::: Verifying CPU governor setting
::: Passed
::: Verifying Scripts
::: Passed (no scripts configured to run)
::: Verifying GPU Optimisations
::: Passed (gpu optimisations not configured to run)
::: Verifying renice
ERROR: renice value not set correctly after gamemode_request_start
Expected: 4, Was: 0
ERROR: Initial values for new threads were incorrect!
ERROR: Multithreaded renice tests failed!
::: Failed!
::: Verifying ioprio
::: Passed
ERROR: :: Failed!
: Tests Failed!
```

**Comment by pongo1231** [comment]
Reinstalling arch seems to have fixed it, not sure what caused it

**Comment by pongo1231** [comment]
Seems like I had to allow users to use negative nice values by editing `/etc/security/limits.conf` (in my case my user is in the `wheel` group so `@wheel - nice -20`). Might be a good idea to document that in the example config file.

**Comment by mikeyjoel** [comment]
> Seems like I had to allow users to use negative nice values by editing `/etc/security/limits.conf` (in my case my user is in the `wheel` group so `@wheel - nice -20`). Might be a good idea to document that in the example config file.

I suggest you add yourself to the gamemode group and add the gamemode group instead of wheel since all processes will have a renice of -20 and you'll want to only apply those renice to your games.
