### ISSUE TITLE
gamemoderun verbosity

### ISSUE THREAD

**Issue by EduFrazao** [FeralInteractive/gamemode#293]
Hi. Its possible to allow more verbosity with gamemoderun wrapper?
I wan't see which config is used, if SCHED_ISO is avaliable and used, informations like if frequency governor is changed, etc.
I can't find this info in the docs.
Thanks!

**Comment by stephanlachnit** [comment]
No, gamemoderun is a very single bash script that only injects a library, which itself is tiny and only notifies the DBus daemon, which does th real work.

You can run `gamemoded -t` if you want a general feature test, or you can check the logs of the daemon via systemd.

**Comment by EduFrazao** [comment]
@stephanlachnit Thank you for your answer. I'm runing gamemode with elogind. Can I see the logs regular syslog?

**Comment by stephanlachnit** [comment]
I'm not familiar with elogind, usually I simply use `systemctl` or `journalctl`, you may look up the equivalent on your setup.

**Comment by EduFrazao** [comment]
@stephanlachnit Do you know if gamemoded -t can test about the usage of softrealtime (SCHED_ISO). I didn't found or didn't recognize any output about it.
I've configure it to "auto", and my kernel supports it:

`$ schedtool -r
N: SCHED_NORMAL  : prio_min 0, prio_max 0
F: SCHED_FIFO    : prio_min 1, prio_max 99
R: SCHED_RR      : prio_min 1, prio_max 99
B: SCHED_BATCH   : prio_min 0, prio_max 0
I: SCHED_ISO     : prio_min 0, prio_max 0
D: SCHED_IDLEPRIO: prio_min 0, prio_max 0`

Here is the output:
`$ gamemoded -t
: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
Loading config file [/home/eduardo/.config/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Passed

:: Supervisor tests
:: Passed

:: Feature tests
::: Verifying CPU governor setting
::: Passed
::: Verifying Scripts
::: Passed (no scripts configured to run)
::: Verifying GPU Optimisations
::: Passed (gpu optimisations not configured to run)
::: Verifying renice
::: Passed (no renice configured)
::: Verifying ioprio
::: Passed
:: Passed

: All Tests Passed!`
