### ISSUE TITLE
gamemode does not support 32-bit games

### ISSUE THREAD

**Issue by omer666** [FeralInteractive/gamemode#30]
It cannot work with 32-bit games as it uses LD_PRELOAD with a 64-bit library. Maybe having a 32-bit compat library for these use cases could be useful.

**Comment by mdiluz** [comment]
Closing as gamemode does support a 32-bit build - as seen on the AUR package or elsewhere.

Adding `-m32` to CFLAGS and appropriate platform arguments to meson will solve the issue.
