### ISSUE TITLE
Additional launch options in Steam?

### ISSUE THREAD

**Issue by digital-carver** [FeralInteractive/gamemode#316]
The instruction to use this with Steam games is to have `gamemoderun %command%` in the Launch Options of the game. How do we add launch options that we wish to have for the game itself?

 For eg., say I wanted to add `-console` option to my Dota 2. Should it be `gamemoderun %command% -console`, or `gamemoderun "%command% -console"`, or something else? (Or - I hope this is not the case - is it not possible to add other launch options when using GameMode?)

**Comment by mdiluz** [comment]
From https://github.com/FeralInteractive/gamemode/blob/master/data/gamemoderun#L9

`gamemoderun %command% -console` should do the trick due to the way it's using `"$@"` in bash

**Comment by digital-carver** [comment]
This seems to be working (and gamemode makes a _big_ difference to the performance). Thanks @mdiluz .
