### ISSUE TITLE
Move to github actions

### ISSUE THREAD

**Issue by stephanlachnit** [FeralInteractive/gamemode#325]
Travis is failing for no apparent reason (or to be more precise, their apt addon is broken), so I suggest to move to GitHub actions. I can provide a PR if you are fine with this change @afayaz-feral.

It's relatively easy to do, we can take this as a base: https://github.com/stephanlachnit/yaiden/blob/main/.github/workflows/build-and-test.yml

**Comment by afayaz-feral** [comment]
I'm happy to make this change, I'll test and approve the PR if you make one.

I was just about to delve into what's going on here so thank you for saving me the trouble. I will hold off approving the other open PRs until this is resolved.
