### ISSUE TITLE
Permission denied on sytemctl 

### ISSUE THREAD

**Issue by as3mbus** [FeralInteractive/gamemode#33]
I installed arch package from AUR
using 
`makepkg -si`
the installation went fine without error
but when i try to enable/start the service using `systemctl --user`
it says 
```
Job for gamemoded.service failed because the control process exited with error code.
See "systemctl --user status gamemoded.service" and "journalctl --user -xe" for details.
```
i check the status it says 
```
Apr 15 17:48:15 A3-laptop systemd[493]: Starting gamemoded...
Apr 15 17:48:15 A3-laptop systemd[2890]: gamemoded.service: Failed to execute command: Permission denied
Apr 15 17:48:15 A3-laptop systemd[2890]: gamemoded.service: Failed at step EXEC spawning /usr/bin/gamemoded: Permission denied
Apr 15 17:48:15 A3-laptop systemd[493]: gamemoded.service: Main process exited, code=exited, status=203/EXEC
Apr 15 17:48:15 A3-laptop systemd[493]: gamemoded.service: Failed with result 'exit-code'.
Apr 15 17:48:15 A3-laptop systemd[493]: Failed to start gamemoded.
```
is the AUR package maintained here as well ?
or should i ask the in AUR comment section instead. 

thankyou.

**Comment by ysblokje** [comment]
Hi @as3mbus, 
I'm the current maintainer of the gamemode AUR package, because of the way archpackages are I suggest you report this problem there. The PKGBUILD in the sourcetree was made during the initial development of the gamemode project as an example.

**Comment by as3mbus** [comment]
okay. thank's for your fast respond :smile:

**Comment by mdiluz** [comment]
I'll close this off - happy to merge PRs with fixes if needed @ysblokje
