### ISSUE TITLE
Show a notification when game mode is started/stopped

### ISSUE THREAD

**Issue by axel358** [FeralInteractive/gamemode#350]
Similar to what the Gnome shell extension game mode does, provide a way to show a notification when a game is launched with game mode that works on all desktop environments

**Comment by mdjose** [comment]
> Similar to what the Gnome shell extension game mode does, provide a way to show a notification when a game is launched with game mode that works on all desktop environments

This is already implemented. Do you setted a configuration file? Check out the "[custom]" session at the bottom of the example configuration.

See: https://github.com/FeralInteractive/gamemode#configuration
