### ISSUE TITLE
Can’t set profile to high on amd gpu

### ISSUE THREAD

**Issue by anyoneyun** [FeralInteractive/gamemode#351]
Hi all, I’m not sure if it’s a bug to be honest, but I guess it is since I tried everything. I’ve installed gamemode to fix the random downclocking that happens with my amd gpu  on some proton games. I’ve looked into gamemode.ini in /usr/share/gamemode/ and I set the correct values to enable the “high” gpu profile. I set apply_gpu_optimisations to 1 as well to “accept-responsibility”, gpu_device to 0, amd_performance_level to high. The gpu is still downclocking and I have to force it to high manually in terminal. I know gamemode is running because I put gamemoderun %command% on Steam launch options and I have a gnome shell extension that tells me when it’s running. Do you have any idea? Thanks.

**Comment by anyoneyun** [comment]
Update. Running the command `gamemoded` returns the following:
```
v1.6.1
Loading config file [/usr/share/gamemode/gamemode.ini]
ERROR: Failed to acquire service name: File exists
```
Running `gamemoded -t` returns this:
```
: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Passed

:: Supervisor tests
:: Passed

:: Feature tests
::: Verifying CPU governor setting
::: Passed
::: Verifying Scripts
::: Passed (no scripts configured to run)
::: Verifying GPU Optimisations
ERROR: Current AMD GPU performance level during gamemode does not match requested value!
        expected:high was:auto
::: Failed!
::: Verifying renice
::: Passed (no renice configured)
::: Verifying ioprio
::: Passed
ERROR: :: Failed!
: Tests Failed!
```

**Comment by kostadin04** [comment]
I managed to fix it by adding `amdgpu.ppfeaturemask=0xffffffff` to my boot flags and then creating a gamemode group and adding my user to it.
https://wiki.archlinux.org/title/AMDGPU#Boot_parameter
`sudo groupadd gamemode`
`sudo usermod -a -G gamemode $(whoami)`

**Comment by mdjose** [comment]
> I managed to fix it by adding `amdgpu.ppfeaturemask=0xffffffff` to my boot flags and then creating a gamemode group and adding my user to it. https://wiki.archlinux.org/title/AMDGPU#Boot_parameter `sudo groupadd gamemode` `sudo usermod -a -G gamemode $(whoami)`

I can confirm the boot flag also fixed it on Arch. Maybe this info should be added to the README?

Thanks @kostadin04 for the findings,
thanks devs for the amazing work.

**Comment by Hrothen** [comment]
> Maybe this info should be added to the README?

And to the Archwiki entry for gamemode as well

**Comment by mdjose** [comment]
> > Maybe this info should be added to the README?
> 
> And to the Archwiki entry for gamemode as well

I agree, check the ArchWiki for the little change I submitted.

**Comment by mdjose** [comment]
I agree, check out the GameMode page in ArchWiki for the little change I submitted.

**Comment by anyoneyun** [comment]
I couldn’t actually replicate the issue. Your solution worked for some people so I’m closing the issue. Thanks!

**Comment by pinbuck** [comment]
> > I managed to fix it by adding `amdgpu.ppfeaturemask=0xffffffff` to my boot flags and then creating a gamemode group and adding my user to it. https://wiki.archlinux.org/title/AMDGPU#Boot_parameter `sudo groupadd gamemode` `sudo usermod -a -G gamemode $(whoami)`
> 
> I can confirm the boot flag also fixed it on Arch. Maybe this info should be added to the README?
> 
> Thanks @kostadin04 for the findings, thanks devs for the amazing work.

What's the best way to undo this? is it safe to groupdel and then just reinstall gamemode again?
Asking because I've had a lot of trouble getting gamemode to work properly in the past with or without this on, not being sure if its the exact culprit.
I saw that, unrelated, the renicing option requires group, but after reading latest release notes i saw something about automatically adding user to group.

also I had much less artifacting with amdgpu.ppfeaturemask=0xfffd7fff, instead of amdgpu.ppfeaturemask=0xffffffff
I believe 0xffffffff also disables power saving features, so maybe that's not a good idea to be recommending to new users.
https://linuxreviews.org/HOWTO_undervolt_the_AMD_RX_4XX_and_RX_5XX_GPUs

**Comment by Calinou** [comment]
> I believe 0xffffffff disables a few power saving features instead of just only allowing overdrive, so amdgpu.ppfeaturemask=0xffffffff is probably not a good idea to be using.

I can confirm the GPU voltage never goes below 775 mV on a Rade on 6900 XT when that feature mask is used, so it's indeed disabling power saving features (while it decreases to a much lower value on the desktop otherwise).

**Comment by nfp0** [comment]
> I can confirm the GPU voltage never goes below 775 mV on a Radeon 6900 XT

What tool are you using to see that value? I see it dropping to 0,0V on KDE's System Monitor but that obviously can't be right.

**Comment by nfp0** [comment]
@mdjose @Hrothen The `amdgpu.ppfeaturemask` does not seem to be necessary anymore, at least on my Manjaro install. I don't know what changed or where. Could you please confirm this on your side? If so, it can be removed from the Arch wiki.

**Comment by Calinou** [comment]
> @Calinou What tool are you using to see that value? I see it dropping to 0,0V on KDE's System Monitor but that obviously can't be right.

I was using `sensors`, but it's likely that the reading is incorrect since a GPU can't use a voltage that low.

**Comment by nfp0** [comment]
Mine drops down to 6 mV, which can't be right.
But it drops down to the more meaningful value of 6 watts, which I believe, because it's the typical idle value for this card.
