### ISSUE TITLE
Gamemode no route to host message on Plasma-Wayland

### ISSUE THREAD

**Issue by raneon** [FeralInteractive/gamemode#37]
I have installed gamemode on Arch Linux and the service seems to run well:

$ systemctl --user status gamemoded 
● gamemoded.service - gamemoded
   Loaded: loaded (/usr/lib/systemd/user/gamemoded.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-04-22 12:08:53 CEST; 18s ago
 Main PID: 1425 (gamemoded)
   CGroup: /user.slice/user-1000.slice/user@1000.service/gamemoded.service
           └─1425 /usr/bin/gamemoded -l

Apr 22 12:08:53 pc /usr/bin/gamemoded[1425]: Note: No config file found [gamemode.ini] in working directory or in [/usr/share/gamemode/]
Apr 22 12:08:53 pc /usr/bin/gamemoded[1425]: governor is set to [schedutil]
Apr 22 12:08:53 pc /usr/bin/gamemoded[1425]: Successfully initialised bus with name [com.feralinteractive.GameMode]...
Apr 22 12:08:53 pc systemd[1419]: Starting gamemoded...
Apr 22 12:08:53 pc systemd[1419]: Started gamemoded.

However if starting a game on Plasma-Wayland, then I get the following message/error:
$ LD_PRELOAD=/usr/\$LIB/libgamemodeauto.so ./game
gamemodeauto: Could not call method on bus: No route to host

**Comment by mdiluz** [comment]
Hi,
The line should be
```
LD_PRELOAD=/usr/\$LIB/libgamemodeauto.so ./game
```

**Comment by mdiluz** [comment]
Hi @raneon, on second thoughts, if gamemodeauto managed to print then the line did at least work. Did you get anywhere further with this?

**Comment by raneon** [comment]
I don't have this issue anymore, so I will close this bug.
