### ISSUE TITLE
Authentication prompt show up every time (Again)

### ISSUE THREAD

**Issue by tedliosu** [FeralInteractive/gamemode#386]
**Describe the bug**
(Related to #138)
Authentication prompt show up every time when request and exit gamemode, and sometimes even repeatedly shows up in the middle of a game. Super user is needed to run /usr/libexec/cpugovctl, and CPU governor doesn't switch from performance back to ondemand unless authenticated.

**To Reproduce**
Steps used to reproduce the behavior:
1. Launch gamemode with any game
2. Authentication prompt show up (sometimes multiple times in the middle of a game, and it won't give me enough time to punch in my password either)
3. Exit the game
4. Authentication prompt shows up again

**Expected behavior**
Gamemode shouldn't prompt for authentication, or if it must be done, it should prompt once only, not every time

**System Info (please complete the following information):**
 - OS and version: Ubuntu 20.04.05
 - GameMode Version: 1.7 HEAD 4934191b1928ef695c3e8af21e75781f8591745f

**Additional context**
No that is all

**Comment by tedliosu** [comment]
Btw I downgraded to version 1.5.1 from the Ubuntu apt repos, and applied the same tweaked policykit config files to the program, and the issue went away; what's wrong with the latest version of gamemode that may be causing this authentication issue?

**Comment by webodan** [comment]
this happens to me also. can't figure out why.

**Comment by tedliosu** [comment]
> this happens to me also. in my case even after editing /etc/polkit-default-privs.standard then rebooting it still asks for root password. can't figure out why.
> 
> edit: actually i found a fix, /usr/local/share/polkit-1/rules.d/gamemode.rules was the culprit, in my system it wanted me to add my user to the gamemode group so that it would stop asking for root. once i deleted that file it went away, but using the repo version like @tedliosu is doing

Dang I see; will try that when I get the chance :eyes:

**Comment by tedliosu** [comment]
Actually, I just tried reproducing the issue again today, and not only could I not find the `/usr/local/share/polkit-1/rules.d/gamemode.rules` file that @webodan had mentioned, but I couldn't get the authentication prompt to constantly appear like it did before when I initially created this issue.  In both cases (today and when I first created this issue), I changed the `<allow_any>` and `<allow_inactive>` tags within the installed `com.feralinteractive.GameMode.policy` file from "no" to "yes", so that definitely couldn't have be related to this issue.  I think it might be that I forgot to checkout the `1.7` tag when I initially installed from the repo when I created this issue initially, hence leading to me running into a potential bug that had been introduced _after_ the latest official release...

Anyway I am closing this issue for now as there appears to be at least a workaround for those who are facing the same issue, and especially as I have been unable to reproduce this issue.
