### ISSUE TITLE
Unable to build on clear linux

### ISSUE THREAD

**Issue by nobbysheep** [FeralInteractive/gamemode#399]
**Describe the bug**
As I can't find any other way to install I'm following the documented approach for building from source however when I run the build fails. Here's the output;

./bootstrap.sh
warning: unable to rmdir 'subprojects/inih': Directory not empty
Previous HEAD position was d58c59c Update version to 1.5
HEAD is now at 4dc99df Specify correct inih directory after update to r54
+ meson builddir --prefix=/usr --buildtype debugoptimized -Dwith-systemd-user-unit-dir=/etc/systemd/user
The Meson build system
Version: 0.64.1
Source dir: /home/paul/code/gamemode
Build dir: /home/paul/code/gamemode/builddir
Build type: native build
Project name: gamemode
Project version: 1.7
C compiler for the host machine: gcc (gcc 12.2.1 "gcc (Clear Linux OS for Intel Architecture) 12.2.1 20221215 releases/gcc-12.2.0-290-g7525c9d7e7")
C linker for the host machine: gcc ld.bfd 2.39.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Waggregate-return: YES 
Compiler for C supports arguments -Wunused: YES 
Compiler for C supports arguments -Warray-bounds: YES 
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wclobbered: YES 
Compiler for C supports arguments -Wempty-body: YES 
Compiler for C supports arguments -Wformat=2: YES 
Compiler for C supports arguments -Wformat-nonliteral: YES 
Compiler for C supports arguments -Wformat-signedness: YES 
Compiler for C supports arguments -Wignored-qualifiers: YES 
Compiler for C supports arguments -Wimplicit-function-declaration: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wmissing-format-attribute: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wmissing-noreturn: YES 
Compiler for C supports arguments -Wmissing-parameter-type: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wno-discarded-qualifiers: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-suggest-attribute=format: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Woverride-init: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wredundant-decls: YES 
Compiler for C supports arguments -Wreturn-type: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wsign-compare: YES 
Compiler for C supports arguments -Wstrict-aliasing=3: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wstringop-overflow: YES 
Compiler for C supports arguments -Wstringop-truncation: YES 
Compiler for C supports arguments -Wtype-limits: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wuninitialized: YES 
Compiler for C supports arguments -Wunused-but-set-variable: YES 
Compiler for C supports arguments -Wwrite-strings: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libsystemd found: YES 251
Run-time dependency dbus-1 found: YES 1.14.4
Run-time dependency threads found: YES
Library dl found: YES
Run-time dependency systemd found: YES 251
Checking for function "pidfd_open" : YES 
Configuring build-config.h using configuration
Found CMake: /usr/bin/cmake (3.25.1)
Run-time dependency inih found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency inih
Downloading inih source from https://github.com/benhoyt/inih/archive/r54.tar.gz
Downloading file of unknown size.

Executing subproject inih 

inih| Project name: inih
inih| Project version: undefined
inih| C compiler for the host machine: gcc (gcc 12.2.1 "gcc (Clear Linux OS for Intel Architecture) 12.2.1 20221215 releases/gcc-12.2.0-290-g7525c9d7e7")
inih| C linker for the host machine: gcc ld.bfd 2.39.0
inih| C++ compiler for the host machine: g++ (gcc 12.2.1 "g++ (Clear Linux OS for Intel Architecture) 12.2.1 20221215 releases/gcc-12.2.0-290-g7525c9d7e7")
inih| C++ linker for the host machine: g++ ld.bfd 2.39.0
inih| Build targets in project: 9
inih| Subproject inih finished.

Dependency inih from subproject subprojects/inih-r54 found: YES undefined
Configuring gamemoded.service using configuration
Configuring com.feralinteractive.GameMode.service using configuration
Configuring com.feralinteractive.GameMode.policy using configuration
Configuring gamemoded.8 using configuration
Configuring gamemoderun.1 using configuration
Configuring gamemodelist.1 using configuration
Configuring gamemode-simulate-game.1 using configuration
Program appstreamcli found: YES (/usr/bin/appstreamcli)
Message: 

    Build configuration:
    ====================

    prefix:                                 /usr
    bindir:                                 /usr/bin
    datadir:                                /usr/share
    libdir:                                 /usr/lib64
    libexecdir:                             /usr/libexec
    includedir:                             /usr/include
    systemd user unit directory:            /etc/systemd/user
    D-BUS service directory:                /usr/share/dbus-1/services
    PolKit Action Directory:                /usr/share/polkit-1/actions

    Options:
    ========

    sd-bus provier:                         systemd
    examples:                               true
    util:                                   true

Build targets in project: 11

gamemode 1.7

  Subprojects
    inih                      : YES

  User defined options
    buildtype                 : debugoptimized
    prefix                    : /usr
    with-systemd-user-unit-dir: /etc/systemd/user

Found ninja-1.11.1 at /usr/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
+ ninja -C builddir
ninja: Entering directory `builddir'
[9/37] Compiling C object common/liblib-common.a.p/common-pidfds.c.o
FAILED: common/liblib-common.a.p/common-pidfds.c.o 
gcc -Icommon/liblib-common.a.p -Icommon -I../common -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c11 -O2 -g -fstack-protector -Wstrict-prototypes -Wundef -fno-common -Werror-implicit-function-declaration -Wformat-security -Werror=format-security -Wconversion -Wunreachable-code -Waggregate-return -Wunused -Warray-bounds -Wcast-align -Wclobbered -Wempty-body -Wformat=2 -Wformat-nonliteral -Wformat-signedness -Wignored-qualifiers -Wimplicit-function-declaration -Winit-self -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-parameter-type -Wnested-externs -Wno-discarded-qualifiers -Wno-missing-field-initializers -Wno-suggest-attribute=format -Wno-unused-parameter -Wold-style-definition -Woverride-init -Wpointer-arith -Wredundant-decls -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing=3 -Wstrict-prototypes -Wstringop-overflow -Wstringop-truncation -Wtype-limits -Wundef -Wuninitialized -Wunused-but-set-variable -Wwrite-strings -g -O3 -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -Wformat -Wformat-security -m64 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z,now -Wl,-z,relro -fno-semantic-interposition -ffat-lto-objects -fno-trapping-math -Wl,-sort-common -Wl,--enable-new-dtags -mtune=skylake -mrelax-cmpxchg-loop -fPIC -MD -MQ common/liblib-common.a.p/common-pidfds.c.o -MF common/liblib-common.a.p/common-pidfds.c.o.d -o common/liblib-common.a.p/common-pidfds.c.o -c ../common/common-pidfds.c
../common/common-pidfds.c: In function ‘open_pidfds’:
../common/common-pidfds.c:70:26: error: implicit declaration of function ‘pidfd_open’; did you mean ‘fdopen’? [-Werror=implicit-function-declaration]
   70 |                 int fd = pidfd_open(pid, 0);
      |                          ^~~~~~~~~~
      |                          fdopen
../common/common-pidfds.c:70:26: warning: nested extern declaration of ‘pidfd_open’ [-Wnested-externs]
cc1: some warnings being treated as errors
[10/37] Compiling C object common/libdaemon-common.a.p/common-pidfds.c.o
FAILED: common/libdaemon-common.a.p/common-pidfds.c.o 
gcc -Icommon/libdaemon-common.a.p -Icommon -I../common -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c11 -O2 -g -fstack-protector -Wstrict-prototypes -Wundef -fno-common -Werror-implicit-function-declaration -Wformat-security -Werror=format-security -Wconversion -Wunreachable-code -Waggregate-return -Wunused -Warray-bounds -Wcast-align -Wclobbered -Wempty-body -Wformat=2 -Wformat-nonliteral -Wformat-signedness -Wignored-qualifiers -Wimplicit-function-declaration -Winit-self -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-parameter-type -Wnested-externs -Wno-discarded-qualifiers -Wno-missing-field-initializers -Wno-suggest-attribute=format -Wno-unused-parameter -Wold-style-definition -Woverride-init -Wpointer-arith -Wredundant-decls -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing=3 -Wstrict-prototypes -Wstringop-overflow -Wstringop-truncation -Wtype-limits -Wundef -Wuninitialized -Wunused-but-set-variable -Wwrite-strings -g -O3 -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -Wformat -Wformat-security -m64 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z,now -Wl,-z,relro -fno-semantic-interposition -ffat-lto-objects -fno-trapping-math -Wl,-sort-common -Wl,--enable-new-dtags -mtune=skylake -mrelax-cmpxchg-loop -fPIC -MD -MQ common/libdaemon-common.a.p/common-pidfds.c.o -MF common/libdaemon-common.a.p/common-pidfds.c.o.d -o common/libdaemon-common.a.p/common-pidfds.c.o -c ../common/common-pidfds.c
../common/common-pidfds.c: In function ‘open_pidfds’:
../common/common-pidfds.c:70:26: error: implicit declaration of function ‘pidfd_open’; did you mean ‘fdopen’? [-Werror=implicit-function-declaration]
   70 |                 int fd = pidfd_open(pid, 0);
      |                          ^~~~~~~~~~
      |                          fdopen
../common/common-pidfds.c:70:26: warning: nested extern declaration of ‘pidfd_open’ [-Wnested-externs]
cc1: some warnings being treated as errors
[18/37] Compiling C++ object subprojects/inih-r54/libINIReader.so.0.p/cpp_INIReader.cpp.o
ninja: build stopped: subcommand failed.

Not too sure what's wrong  / missing

**Expected behavior**
Build should not fail

**System Info (please complete the following information):**
 - OS and version: Clear Linux 37780
 - GameMode Version: 1.7

**Additional context**
I believe i've installed all of the required packages but new to clear linux so may have missed something very obvious

**Comment by nobbysheep** [comment]
Seems to be typo in 1.7 so swapped to master and build worked. Managed to install but test run (using gamemoded -t) seems to fail;

gamemode request succeeded and is active
Quitting by request...
: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
:: Passed

:: Gamemoderun and reaper thread tests
: Loading config
Loading config file [/usr/share/gamemode/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Supervisor tests
:: Passed

: Client tests failed, skipping feature tests
: Tests Failed!

**Comment by nobbysheep** [comment]
NOTE ; might be worth updating documentation referencing ver 1.7

**Comment by sazaland** [comment]
For me, using Meson 1.0.0 got past this when building the master. May work for you as well.

**Comment by 8lendzior** [comment]
I have fixed the issue by changing line 29 in bootstrap.sh to:
#### meson **setup** builddir --prefix=$prefix --buildtype debugoptimized -Dwith-systemd-user-unit-dir=/etc/systemd/user "$@"
before running the script

**Comment by nobbysheep** [comment]
Thanks - I've actually switched from Clearlinux to EnveavourOS which is pretty much as performant but not saddled with having to jump through hoops to get software working. If I swap back I'll be sure to try this out. Thanks again
