### ISSUE TITLE
Failed to enable unit: Unit file gamemoded.service does not exist.

### ISSUE THREAD

**Issue by poke86** [FeralInteractive/gamemode#40]
EDIT : Xubuntu not Ubuntu

Hello, I'm trying to install gamemode but it fails. I did exactly as the readme says.

Xubuntu 18.04, nvidia 396.18 drivers.

`$ ./bootstrap.sh 
+ meson --prefix=/usr build -Dwith-systemd-user-unit-dir=/etc/systemd/user
Directory already configured, exiting Meson. Just run your build command
(e.g. ninja) and Meson will regenerate as necessary. If ninja fails, run ninja
reconfigure to force Meson to regenerate.

If build failures persist, manually wipe your build directory to clear any
stored system data.

To change option values, run meson configure instead.
+ cd build
+ ninja
ninja: no work to do.
+ set +x
Install to /usr? [Yy] y
+ sudo ninja install
[0/1] Installing files.
Installing lib/libgamemode.so to /usr/lib/x86_64-linux-gnu/libgamemode.so
Installing lib/libgamemodeauto.so to /usr/lib/x86_64-linux-gnu/libgamemodeauto.so
Installing daemon/gamemoded to /usr/bin/gamemoded
Installing daemon/cpugovctl to /usr/libexec/cpugovctl
Installing gamemode_client.h to /usr/include/
Installing /GAMES/gamemode/gamemode-1.0/data/gamemoded.1 to /usr/share/man/man1
Installing /GAMES/gamemode/gamemode-1.0/build/data/gamemoded.service to /etc/systemd/user
Installing /GAMES/gamemode/gamemode-1.0/build/data/com.feralinteractive.GameMode.policy to /usr/share/polkit-1/actions
+ set +x
Enable and run the daemon? [Yy] y
+ systemctl --user daemon-reload
+ systemctl --user enable gamemoded
Failed to enable unit: Unit file gamemoded.service does not exist.`

**Comment by poke86** [comment]
I should add that locating gamemoded.service does find something : 

$ locate gamemoded.service
/etc/systemd/user/gamemoded.service

**Comment by mdiluz** [comment]
Tagged as help wanted as I'm unsure what could be failing in systemctl there.

Stupid question though but does this still fail after a reboot?

**Comment by poke86** [comment]
Hello, thanks for the reply.

I haven't tried rebooting specifically to try and install again, but I did try it several times with my computer being off in between. No luck.

It was the same in Xubuntu 16.04 btw.

**Comment by poke86** [comment]
It's not happening anymore, not sure what changed.
