### ISSUE TITLE
Feature: disable Redshift

### ISSUE THREAD

**Issue by thomas-mc-work** [FeralInteractive/gamemode#41]
[Redshift](http://jonls.dk/redshift/):

> Redshift adjusts the color temperature of your screen according to your surroundings. This may help your eyes hurt less if you are working in front of the screen at night.

It would be nice if gamemode could disable Redshift while active.

**Comment by ysblokje** [comment]
I think your best bet would be to use the feature from this d26aac7147efe732c82c76074156bda66eda9ac3 commit. 
Personally I would hate the have my redshift taken from me when I start a game.

**Comment by mdiluz** [comment]
Cheers @ysblokje, that's correct. `pkill -USR1 redshift` should be enough in the start and end sections in the config.

**Comment by thomas-mc-work** [comment]
@ysblokje custom scripts looks good. Everything else is a matter of taste…

**Comment by mdiluz** [comment]
For any future google-wizards who find themselves here, as far as I know you can use this for NightShift as well:

```
[custom]
start=gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled false
end=gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
```
