### ISSUE TITLE
Feature request: Allow automatically disabling split lock mitigations while Gamemode is running

### ISSUE THREAD

**Issue by brndd** [FeralInteractive/gamemode#425]
**Is your feature request related to a problem? Please describe.**
Some Windows games [trigger the kernel's split lock mitigation feature](https://www.phoronix.com/news/Linux-Splitlock-Hurts-Gaming), which artificially slows down apps that abuse split locks. It is unlikely that these developers will stop abusing split locks for the time being, so disabling this mitigation while playing the game using `sudo sysctl kernel.split_lock_mitigate=0` is the only solution.

**Describe the solution you'd like**
Gamemode could have a toggleable switch to automatically disable split lock mitigations while a game is running and then re-enable them when the game exits.

**Describe alternatives you've considered**
Disabling split lock mitigation manually works, but is a bit tedious. Automating it with a script is annoying, because the command requires root privileges. Gamemode custom scripts do not currently seem to support an "exit script" that is run when the game exists, so those are not an option? Disabling split lock entirely by setting a boot flag is a bit of a nuclear solution, because this feature is nice to have enabled in general, just not when it makes games unplayable.

**Additional context**
God of War and [Street Fighter 6](https://github.com/ValveSoftware/Proton/issues/6817#issuecomment-1595495268) are examples of games that have this issue.

**Comment by HenrikHolst** [comment]
I have written support for this on my fork here: https://github.com/HenrikHolst/gamemode/tree/HenrikHolst-patch-1
