### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by nanonyme** [FeralInteractive/gamemode#429]
Any chance getting a new release done at some point soon? This project doesn't now support glibc 2.36 due to https://github.com/FeralInteractive/gamemode/commit/4934191b1928ef695c3e8af21e75781f8591745f not being in any release tag.

**Comment by orowith2os** [comment]
We are encountering the same problem in [Vinegar](https://github.com/flathub/io.github.vinegarhq.Vinegar/pull/34) and inevitably will on many other projects too. It appears the Steam Flatpak backports that patch, for example.

**Comment by nanonyme** [comment]
Ping @afayaz-feral can this be handled? This is only going to get worse over the year.

**Comment by afayaz-feral** [comment]
I've now done a release of 1.8, so closing this. Let me know if there's anything that needs my attention.
