### ISSUE TITLE
Test failed 

### ISSUE THREAD

**Issue by ricandresfriki97** [FeralInteractive/gamemode#459]
The performance is badly after I upgrade the gamemode 1.7.0 to 1.8.1 so I put in the terminal "gamemoded -t" in this appears 
:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Passed

:: Supervisor tests
:: Passed

:: Feature tests
::: Verifying CPU governor setting
ERROR: Governor was not set to performance (was actually powersave)!
::: Failed!
::: Verifying Scripts
::: Passed (no scripts configured to run)
::: Verifying GPU Optimisations
::: Passed (gpu optimisations not configured to run)
::: Verifying renice
::: Passed (no renice configured)
::: Verifying ioprio
::: Passed
ERROR: :: Failed!
: Tests Failed!
I am running this on Ubuntu 23.04 gnome 44.03 in 6.7 kernel 
 I'm sorry if my English is I little odd , this language is not my mother tongue
I hope someone can help me with this issues , thanks

**Comment by leinardi** [comment]
@ricandresfriki97 Hey I have the same issue, how did you solve?

**Comment by Nano-Ocelot** [comment]
> @ricandresfriki97 Hey I have the same issue, how did you solve?

Yeah, I have the same issue. Gamemode no longer functions at all for me. Has this been fixed and the commit just wasn't mentioned in the issue?
