### ISSUE TITLE
Failed to build on Linux mint 18.3

### ISSUE THREAD

**Issue by MrMuttons** [FeralInteractive/gamemode#47]
> + meson --prefix=/usr build -Dwith-systemd-user-unit-dir=/etc/systemd/user
> The Meson build system
> Version: 0.40.1
> Source dir: /home/john/gamemode
> Build dir: /home/john/gamemode/build
> Build type: native build
> Project name: gamemode
> Native c compiler: cc (gcc 5.4.0)
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Found pkg-config: /usr/bin/pkg-config (0.29.1)
> Native dependency libsystemd found: YES 229
> Dependency threads found: YES
> Library dl found: YES
> Configuring config.h using configuration
> error: could not lock config file .git/config: Permission denied
> Failed to register url for submodule path 'inih'
> 
> Meson encountered an error in file meson.build, line 86, column 4:
> Subproject directory 'subprojects/inih' does not exist and cannot be downloaded:
> No inih.wrap found for 'subprojects/inih'

Not sure if this is the same issue as the others related to mint.

**Comment by mdiluz** [comment]
> error: could not lock config file .git/config: Permission denied

This looks like a permissions issue in the checked out directory. Perhaps delete it and try again, preferably using the 1.1 or master branch.

**Comment by MrMuttons** [comment]
After re-downloading the master to my desktop, it installs, but fails at here
```
Enable and run the daemon? [Yy] Y
+ systemctl --user daemon-reload
+ systemctl --user enable gamemoded
+ systemctl --user start gamemoded
Job for gamemoded.service failed because the control process exited with error code. See "systemctl --user status gamemoded.service" and "journalctl -xe" for details.
```

**Comment by MrMuttons** [comment]
Upon running 
systemctl --user status gamemoded.service i get the following
```
systemctl --user status gamemodded.service
● gamemodded.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```
Upon running journalctl -xe i get this

```
May 09 14:49:44 Megumin sudo[27949]:     john : TTY=pts/0 ; PWD=/home/john/Desktop/gamemode/build ; USER=root ; COMMAND=/usr/bin/ninja install
May 09 14:49:44 Megumin sudo[27949]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 09 14:49:44 Megumin sudo[27949]: pam_unix(sudo:session): session closed for user root
May 09 14:49:45 Megumin systemd[2571]: Reloading.
May 09 14:49:45 Megumin systemd[2571]: Reloading.
May 09 14:49:45 Megumin systemd[2571]: Starting gamemoded...
-- Subject: Unit UNIT has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has begun starting up.
May 09 14:49:45 Megumin /usr/bin/gamemoded[28422]: Broken glob implementation (No such file or directory)
May 09 14:49:45 Megumin systemd[2571]: gamemoded.service: Main process exited, code=exited, status=1/FAILURE
May 09 14:49:45 Megumin systemd[2571]: Failed to start gamemoded.
-- Subject: Unit UNIT has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has failed.
-- 
-- The result is failed.
May 09 14:49:45 Megumin systemd[2571]: gamemoded.service: Unit entered failed state.
May 09 14:49:45 Megumin systemd[2571]: gamemoded.service: Failed with result 'exit-code'.

```

**Comment by MrMuttons** [comment]
@mdiluz Issue persists. any help?

**Comment by mdiluz** [comment]
Is it possible you're hit by #44? ie. your CPU/kernel doesn't currently support scaling?

**Comment by MrMuttons** [comment]
trying new build now
