### ISSUE TITLE
[Request] Create a new release

### ISSUE THREAD

**Issue by Anninzy** [FeralInteractive/gamemode#473]
Hi, I'm currently using the Flatpak release of Lutris, and need to update GameMode to include a [recently merged PR](https://github.com/FeralInteractive/gamemode/pull/466). I was [suggested](https://github.com/bdwalton/inhibit-bridge/issues/1#issuecomment-2027243968) to ask for a new release of GameMode, is that possible?

**Comment by justinnichols** [comment]
+1 to this.  It's been 6 months since the last release and the inhibit fix is greatly appreciated.
