### ISSUE TITLE
Ubuntu 18.04: Failed to connect to bus: No such file or directory

### ISSUE THREAD

**Issue by Falc77** [FeralInteractive/gamemode#48]
I get the error in the title when installing gamemode:

```
jamie@jamie-ncase:~$ wget https://github.com/FeralInteractive/gamemode/archive/1.0.tar.gz && tar -xvf 1.0.tar.gz
--2018-05-09 19:51:55--  https://github.com/FeralInteractive/gamemode/archive/1.0.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/FeralInteractive/gamemode/tar.gz/1.0 [following]
--2018-05-09 19:51:56--  https://codeload.github.com/FeralInteractive/gamemode/tar.gz/1.0
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21279 (21K) [application/x-gzip]
Saving to: ‘1.0.tar.gz’

1.0.tar.gz          100%[===================>]  20.78K  --.-KB/s    in 0.1s    

2018-05-09 19:51:56 (208 KB/s) - ‘1.0.tar.gz’ saved [21279/21279]

gamemode-1.0/
gamemode-1.0/.clang-format
gamemode-1.0/.gitignore
gamemode-1.0/CHANGELOG
gamemode-1.0/LICENSE.txt
gamemode-1.0/README.md
gamemode-1.0/bootstrap.sh
gamemode-1.0/daemon/
gamemode-1.0/daemon/cpugovctl.c
gamemode-1.0/daemon/daemon_config.c
gamemode-1.0/daemon/daemon_config.h
gamemode-1.0/daemon/daemonize.c
gamemode-1.0/daemon/daemonize.h
gamemode-1.0/daemon/dbus_messaging.c
gamemode-1.0/daemon/dbus_messaging.h
gamemode-1.0/daemon/gamemode.c
gamemode-1.0/daemon/gamemode.h
gamemode-1.0/daemon/governors-query.c
gamemode-1.0/daemon/governors-query.h
gamemode-1.0/daemon/governors.c
gamemode-1.0/daemon/governors.h
gamemode-1.0/daemon/logging.c
gamemode-1.0/daemon/logging.h
gamemode-1.0/daemon/main.c
gamemode-1.0/daemon/meson.build
gamemode-1.0/data/
gamemode-1.0/data/com.feralinteractive.GameMode.policy.in
gamemode-1.0/data/com.feralinteractive.GameMode.service.in
gamemode-1.0/data/gamemoded.1
gamemode-1.0/data/gamemoded.service.in
gamemode-1.0/data/meson.build
gamemode-1.0/example/
gamemode-1.0/example/archlinux/
gamemode-1.0/example/archlinux/gamemode-git/
gamemode-1.0/example/archlinux/gamemode-git/PKGBUILD
gamemode-1.0/example/archlinux/readme.txt
gamemode-1.0/example/gamemode.ini
gamemode-1.0/example/main.c
gamemode-1.0/example/meson.build
gamemode-1.0/lib/
gamemode-1.0/lib/client_impl.c
gamemode-1.0/lib/client_loader.c
gamemode-1.0/lib/gamemode_client.h
gamemode-1.0/lib/meson.build
gamemode-1.0/meson.build
gamemode-1.0/meson_options.txt
gamemode-1.0/subprojects/
gamemode-1.0/subprojects/inih.wrap
jamie@jamie-ncase:~$ cd gamemode-1.0
jamie@jamie-ncase:~/gamemode-1.0$ sudo ./bootstrap.sh
+ meson --prefix=/usr build -Dwith-systemd-user-unit-dir=/etc/systemd/user
The Meson build system
Version: 0.45.1
Source dir: /home/jamie/gamemode-1.0
Build dir: /home/jamie/gamemode-1.0/build
Build type: native build
Project name: gamemode
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency libsystemd found: YES 237
Dependency threads found: YES
Library dl found: YES
Configuring config.h using configuration
Cloning into 'inih'...
remote: Counting objects: 341, done.
remote: Total 341 (delta 0), reused 0 (delta 0), pack-reused 341
Receiving objects: 100% (341/341), 64.08 KiB | 585.00 KiB/s, done.
Resolving deltas: 100% (203/203), done.

Executing subproject inih.

Project name: inih
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Build targets in project: 3

Subproject inih finished.
Configuring gamemoded.service using configuration
Configuring com.feralinteractive.GameMode.policy using configuration
Message: 


    Build configuration:
    ====================

    prefix:                                 /usr
    bindir:                                 /usr/bin
    datadir:                                /usr/share
    libdir:                                 /usr/lib/x86_64-linux-gnu
    libexecdir:                             /usr/libexec
    includedir:                             /usr/include
    systemd user unit directory:            /etc/systemd/user
    PolKit Action Directory:                /usr/share/polkit-1/actions

    Options:
    ========

    daemon:                                 true
    examples:                               true
    systemd:                                true


Build targets in project: 7
Found ninja-1.8.2 at /usr/bin/ninja
+ cd build
+ ninja
[20/20] Linking target daemon/gamemoded.
+ set +x
Install to /usr? [Yy] y
+ sudo ninja install
[0/1] Installing files.
Installing lib/libgamemode.so to /usr/lib/x86_64-linux-gnu/libgamemode.so
Installing lib/libgamemodeauto.so to /usr/lib/x86_64-linux-gnu/libgamemodeauto.so
Installing daemon/gamemoded to /usr/bin/gamemoded
Installing daemon/cpugovctl to /usr/libexec/cpugovctl
Installing gamemode_client.h to /usr/include/
Installing /home/jamie/gamemode-1.0/data/gamemoded.1 to /usr/share/man/man1
Installing /home/jamie/gamemode-1.0/build/data/gamemoded.service to /etc/systemd/user
Installing /home/jamie/gamemode-1.0/build/data/com.feralinteractive.GameMode.policy to /usr/share/polkit-1/actions
+ set +x
Enable and run the daemon? [Yy] y
+ systemctl --user daemon-reload
Failed to connect to bus: No such file or directory

```

**Comment by m-svo** [comment]
Try 
apt install dbus-user-session
And reboot

**Comment by Falc77** [comment]
I've tried that, but dbus-user-session is already installed. So I tried purging it (so I could try reinstalling it after). I get this message. I don't think there is a problem but I'm not 100% sure:
`jamie@jamie-ncase:~$ sudo apt install dbus-user-session
[sudo] password for jamie: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dbus-user-session is already the newest version (1.12.2-1ubuntu1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
jamie@jamie-ncase:~$ sudo apt purge dbus-user-session
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 libautopilot-gtk : Depends: python-autopilot (>= 1.4) but it is not going to be installed or
                             python3-autopilot (>= 1.4) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
jamie@jamie-ncase:~$ sudo apt install  python3-autopilot
Reading package lists... Done
Building dependency tree... 50%
Building dependency tree       
Reading state information... Done
python3-autopilot is already the newest version (1.6.0+17.04.20170313-0ubuntu3).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
jamie@jamie-ncase:~$ 
`

**Comment by m-svo** [comment]
Looks like you cannot install or update any package at the moment due to some broken dependencies. What happens if you try
apt update
apt upgrade

**Comment by Falc77** [comment]
```
jamie@jamie-ncase:~$ sudo apt update
Hit:1 http://linux.teamviewer.com/deb stable InRelease
Hit:2 http://linux.teamviewer.com/deb preview InRelease                        
Hit:3 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease    
Hit:4 http://gb.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Hit:6 http://gb.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:7 http://ppa.launchpad.net/mozillateam/thunderbird-next/ubuntu bionic InRelease
Hit:8 http://gb.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:9 http://ppa.launchpad.net/numix/ppa/ubuntu bionic InRelease              
Hit:10 http://ppa.launchpad.net/openmw/openmw/ubuntu bionic InRelease        
Hit:11 http://ppa.launchpad.net/tista/adapta/ubuntu bionic InRelease         
Hit:12 http://ppa.launchpad.net/ubuntubudgie/backports/ubuntu bionic InRelease
Hit:13 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease
Reading package lists... Done                      
Building dependency tree       
Reading state information... Done
All packages are up-to-date.
jamie@jamie-ncase:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

```

**Comment by m-svo** [comment]
I don't have enough experience to help you fix dependencies issue (it can break the system) and I'm not sure it matters considering that all packages are up to date. Hopefully someone will give a tip how to troubleshoot this further.

**Comment by Falc77** [comment]
The latest Gamemode version (1.1) seems to have fixed my issue, thanks!

**Comment by ohot2015** [comment]
> Try
> apt install dbus-user-session
> And reboot
my server crashed after reboot
ssh is no longer available

**Comment by vlados1994** [comment]
> Try
> apt install dbus-user-session
> And reboot

fuck you off

**Comment by BoBXygene** [comment]
gamemoded try to access the bus at "/run/user/1000/bus" but theres nothing there.

On my ubuntu V19.10 theres a "/run/user/1000/dbus-1/" , so it means the the bootstrap.sh hardcodes a dbus path which is wrong.

getresuid([1000], [1000], [1000])       = 0
getresgid([1000], [1000], [1000])       = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/run/user/1000/bus"}, 20) = 0
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
geteuid()                               = 1000
getsockname(3, {sa_family=AF_UNIX}, [128->2]) = 0
poll([{fd=3, events=POLLOUT}], 1, 0)    = 1 ([{fd=3, revents=POLLOUT}])
sendto(3, "\0", 1, MSG_NOSIGNAL, NULL, 0) = 1
sendto(3, "AUTH EXTERNAL 31303030\r\n", 24, MSG_NOSIGNAL, NULL, 0) = 24
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
read(3, "OK 6d3bab00b0a0395fc9f437d15ddc5"..., 2048) = 37
poll([{fd=3, events=POLLOUT}], 1, -1)   = 1 ([{fd=3, revents=POLLOUT}])
sendto(3, "NEGOTIATE_UNIX_FD\r\n", 19, MSG_NOSIGNAL, NULL, 0) = 19
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
read(3, "AGREE_UNIX_FD\r\n", 2048)      = 15
poll([{fd=3, events=POLLOUT}], 1, -1)   = 1 ([{fd=3, revents=POLLOUT}])
sendto(3, "BEGIN\r\n", 7, MSG_NOSIGNAL, NULL, 0) = 7
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\0\0\0\0\1\0\0\0n\0\0\0\1\1o\0\25\0\0\0/org/fre"..., iov_len=128}, {iov_base="", iov_len=0}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 128
poll([{fd=3, events=POLLIN}], 1, 25000) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\2\1\1\n\0\0\0\1\0\0\0=\0\0\0\6\1s\0\5\0\0\0:1.66\0\0\0"..., iov_len=2048}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 260
recvmsg(3, {msg_namelen=0}, MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
syscall_0x1b2(0x1652, 0, 0x563be8326010, 0x563be832a760, 0, 0) = 0x4
syscall_0x1b2(0x1652, 0, 0x7fcebe09894d, 0, 0, 0) = 0x5
fcntl(4, F_DUPFD_CLOEXEC, 3)            = 6
fcntl(5, F_DUPFD_CLOEXEC, 3)            = 7
sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\10\0\0\0\2\0\0\0\250\0\0\0\1\1o\0\36\0\0\0/com/fer"..., iov_len=184}, {iov_base="\0\0\0\0\1\0\0\0", iov_len=8}], msg_iovlen=2, msg_control=[{cmsg_len=24, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, cmsg_data=[6, 7]}], msg_controllen=24, msg_flags=0}, MSG_NOSIGNAL) = 192
close(6)                                = 0
close(7)                                = 0
poll([{fd=3, events=POLLIN}], 1, 25000) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\2\1\1\4\0\0\0\21\0\0\0-\0\0\0\5\1u\0\2\0\0\0\6\1s\0\5\0\0\0"..., iov_len=2048}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 68
recvmsg(3, {msg_namelen=0}, MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
close(4)                                = 0
close(5)                                = 0
getpid()                                = 5714
syscall_0x1b2(0x1652, 0, 0x563be8326010, 0x563be832ac60, 0x9, 0) = 0x4
syscall_0x1b2(0x1652, 0, 0x7fcebe09894d, 0x9, 0, 0) = 0x5
fcntl(4, F_DUPFD_CLOEXEC, 3)            = 6
fcntl(5, F_DUPFD_CLOEXEC, 3)            = 7
sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\10\0\0\0\3\0\0\0\250\0\0\0\1\1o\0\36\0\0\0/com/fer"..., iov_len=184}, {iov_base="\0\0\0\0\1\0\0\0", iov_len=8}], msg_iovlen=2, msg_control=[{cmsg_len=24, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, cmsg_data=[6, 7]}], msg_controllen=24, msg_flags=0}, MSG_NOSIGNAL) = 192
close(6)                                = 0
close(7)                                = 0
poll([{fd=3, events=POLLIN}], 1, 25000) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\2\1\1\4\0\0\0\22\0\0\0-\0\0\0\5\1u\0\3\0\0\0\6\1s\0\5\0\0\0"..., iov_len=2048}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 68
recvmsg(3, {msg_namelen=0}, MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
close(4)                                = 0
close(5)                                = 0
write(2, "Failed to request gamemode start"..., 38Failed to request gamemode start: ...

**Comment by BoBXygene** [comment]
When building it knows the right path though :+1: 

franck@PUNCH:/home/franck/Downloads/linux/Feral_GameMode/gamemode/ ?0 !2008
~/Downloads/linux/Feral_GameMode/gamemode/./bootstrap.sh 
+ meson --prefix=/usr build --buildtype debugoptimized -Dwith-systemd-user-unit-dir=/etc/systemd/user
The Meson build system
Version: 0.51.2
Source dir: /home/franck/Downloads/linux/Feral_GameMode/gamemode
Build dir: /home/franck/Downloads/linux/Feral_GameMode/gamemode/build
Build type: native build
Project name: gamemode
Project version: 1.5-dev
C compiler for the host machine: cc (gcc 9.2.1 "cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports arguments -Waggregate-return: YES 
Compiler for C supports arguments -Wunused: YES 
Compiler for C supports arguments -Warray-bounds: YES 
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wclobbered: YES 
Compiler for C supports arguments -Wempty-body: YES 
Compiler for C supports arguments -Wformat=2: YES 
Compiler for C supports arguments -Wformat-nonliteral: YES 
Compiler for C supports arguments -Wformat-signedness: YES 
Compiler for C supports arguments -Wignored-qualifiers: YES 
Compiler for C supports arguments -Wimplicit-function-declaration: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wmissing-format-attribute: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wmissing-noreturn: YES 
Compiler for C supports arguments -Wmissing-parameter-type: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wno-discarded-qualifiers -Wdiscarded-qualifiers: YES 
Compiler for C supports arguments -Wno-missing-field-initializers -Wmissing-field-initializers: YES 
Compiler for C supports arguments -Wno-suggest-attribute=format -Wsuggest-attribute=format: YES 
Compiler for C supports arguments -Wno-unused-parameter -Wunused-parameter: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Woverride-init: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wredundant-decls: YES 
Compiler for C supports arguments -Wreturn-type: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wsign-compare: YES 
Compiler for C supports arguments -Wstrict-aliasing=3: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wstringop-overflow: YES 
Compiler for C supports arguments -Wstringop-truncation: YES 
Compiler for C supports arguments -Wtype-limits: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wuninitialized: YES 
Compiler for C supports arguments -Wunused-but-set-variable: YES 
Compiler for C supports arguments -Wwrite-strings: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency libsystemd found: YES 242
Run-time dependency dbus-1 found: YES 1.12.14
Run-time dependency threads found: YES 
Library dl found: YES
Checking for function "pidfd_open" : NO 
Configuring build-config.h using configuration

|Executing subproject inih method meson 
|
|Project name: inih
|Project version: undefined
|C compiler for the host machine: cc (gcc 9.2.1 "cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008")
|Build targets in project: 7
|Subproject inih finished.

Configuring gamemoded.service using configuration
Configuring com.feralinteractive.GameMode.service using configuration
Configuring com.feralinteractive.GameMode.policy using configuration
Configuring gamemoderun using configuration
Configuring gamemoded.8 using configuration
Message: 


    Build configuration:
    ====================

    prefix:                                 /usr
    bindir:                                 /usr/bin
    datadir:                                /usr/share
    libdir:                                 /usr/lib/x86_64-linux-gnu
    libexecdir:                             /usr/libexec
    includedir:                             /usr/include
    systemd user unit directory:            /etc/systemd/user
    D-BUS service directory:                /usr/share/dbus-1/services
    PolKit Action Directory:                /usr/share/polkit-1/actions

    Options:
    ========

    daemon:                                 true
    examples:                               true
    util:                                   true
    systemd:                                true


Build targets in project: 9
Found ninja-1.9.0 at /usr/bin/ninja
+ cd build
+ ninja
[16/32] Compiling C object 'subprojects/inih/7140a9f@@inih@sta/ini.c.o'.
In file included from /usr/include/string.h:494,
                 from ../subprojects/inih/ini.c:16:
In function ‘strncpy’,
    inlined from ‘strncpy0’ at ../subprojects/inih/ini.c:73:5,
    inlined from ‘ini_parse_stream’ at ../subprojects/inih/ini.c:191:17:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ specified bound 50 equals destination size [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘strncpy0’ at ../subprojects/inih/ini.c:73:5,
    inlined from ‘ini_parse_stream’ at ../subprojects/inih/ini.c:167:17:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ specified bound 50 equals destination size [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[32/32] Linking target daemon/gamemoded.
+ set +x
Install to /usr? [y/N] y
+ sudo ninja install
[0/1] Installing files.
Installing lib/libgamemode.so.0.0.0 to /usr/lib/x86_64-linux-gnu
Installing lib/libgamemodeauto.so.0.0.0 to /usr/lib/x86_64-linux-gnu
Installing util/cpugovctl to /usr/libexec
Installing util/gpuclockctl to /usr/libexec
Installing daemon/gamemoded to /usr/bin
Installing /home/franck/Downloads/linux/Feral_GameMode/gamemode/lib/gamemode_client.h to /usr/include
Installing /home/franck/Downloads/linux/Feral_GameMode/gamemode/build/data/gamemoded.8 to /usr/share/man/man8
Installing /home/franck/Downloads/linux/Feral_GameMode/gamemode/build/meson-private/gamemode.pc to /usr/lib/x86_64-linux-gnu/pkgconfig
Installing /home/franck/Downloads/linux/Feral_GameMode/gamemode/build/meson-private/gamemode-auto.pc to /usr/lib/x86_64-linux-gnu/pkgconfig
Installing /home/franck/Downloads/linux/Feral_GameMode/gamemode/build/data/gamemoded.service to /etc/systemd/user
Installing /home/franck/Downloads/linux/Feral_GameMode/gamemode/build/data/com.feralinteractive.GameMode.service to /usr/share/dbus-1/services
Installing /home/franck/Downloads/linux/Feral_GameMode/gamemode/build/data/com.feralinteractive.GameMode.policy to /usr/share/polkit-1/actions
Installing /home/franck/Downloads/linux/Feral_GameMode/gamemode/build/data/gamemoderun to /usr/bin
+ systemctl --user daemon-reload
