### ISSUE TITLE
MIssing inih.wrap from 1.1 release

### ISSUE THREAD

**Issue by egon2003** [FeralInteractive/gamemode#50]
The 1.1 release tar.gz is missing subprojects/inih.wrap file I believe. I get the following error when running "meson --prefix=/usr build -Dwith-systemd-user-unit-dir=/etc/systemd/user"

When doing the following it works:

git clone https://github.com/FeralInteractive/gamemode.git
cd gamemode
git checkout 1.1

The Meson build system
Version: 0.46.0
Source dir: /home/erik/temp/dfd/gamemode-1.1
Build dir: /home/erik/temp/dfd/gamemode-1.1/build
Build type: native build
Project name: gamemode
Native C compiler: cc (gcc 8.1.0 "gcc (Gentoo 8.1.0-r2 p1.2) 8.1.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Native dependency libsystemd found: YES 238
Dependency threads found: YES
Library dl found: YES
Configuring config.h using configuration

Dependency inih not found but it is available in a sub-subproject.
To use it in the current project, promote it by going in the project source
root and issuing the following command.

meson wrap promote subprojects/inih

meson.build:86:4: ERROR:  Subproject directory 'subprojects/inih' does not exist and cannot be downloaded:
No inih.wrap found for 'subprojects/inih'

A full log can be found at /home/erik/temp/dfd/gamemode-1.1/build/meson-logs/meson-log.txt

**Comment by VanackSabbadium** [comment]
Same issue right here.

**Comment by VanackSabbadium** [comment]
Alright, just followed these instructions instead of downloading the .zip:

`git clone https://github.com/FeralInteractive/gamemode.git
cd gamemode
git checkout 1.1
./bootstrap.sh`

Now it compiles and works.

**Comment by mdiluz** [comment]
Unfortunately, since we're using git submodules the tar/zip options from github won't work, you'll need to use [mkrelease.sh](https://github.com/FeralInteractive/gamemode/blob/master/scripts/mkrelease.sh) to generate a tar ball, or check things out with git directly (and let meson sort out the submodules).

**Comment by ysblokje** [comment]
The aur package(s) is working now that I switched to using git tags. Thanks for the suggestion @mdiluz.

**Comment by mdiluz** [comment]
FWIW this is discussed in more detail here: https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release.

One solution would be to add a generated tar ball using `mkrelease.sh` to a release branch, and check that in. That way it'll be there within the already generated GitHub download, and will just need a double extract? It's not exactly pretty though.

**Comment by highvoltage** [comment]
Is it possible to rather build gamemode using the inih from my distribution?

**Comment by mdiluz** [comment]
Yup, that should be doable with a modification to meson

**Comment by mdiluz** [comment]
I've updated the release notes here with a warning that the zip and tar files won't work.

**Comment by ikeydoherty** [comment]
? This is why we have `mkrelease.sh` to generate a fully working tarball to attach on the releases page @mdiluz

**Comment by mdiluz** [comment]
Ye know, I couldn't find the way to attach a file there last time I checked, but yup, it's there. I'll sort that out!

**Comment by ikeydoherty** [comment]
xD

**Comment by mdiluz** [comment]
Ok, 1.1 should now have a nice healthy tar.xz file on the update.

Re-opening until someone verifies it works.

**Comment by ysblokje** [comment]
@mdiluz like @egon2003  says, it works.
Much better, thanks.

**Comment by mdiluz** [comment]
Cheers, apologies for the derp
