### ISSUE TITLE
Not installed on Fedora 41

### ISSUE THREAD

**Issue by blunelsongamer** [FeralInteractive/gamemode#504]
**Describe the bug**
So I exactly install the dependencies as said, and i'm trying to run the bootstrap from terminal, and it has errors. What did i do wrong?
**To Reproduce**

[meson-log.txt](https://github.com/user-attachments/files/17602338/meson-log.txt)

**Expected behavior**
Maybe it wasn't ready yet since this is already a new version of fedora. So I do hope they can find a way to fix it.

**System Info (please complete the following information):**
 - OS and version: Fedora 41
 - GameMode Version git sha
 
**Additional context**
It did say that it has compiling errors, stating that they find it unknown. It can't even find cmake and inih despite i already install the dependencies required.

**Comment by perkyquirky** [comment]
I think this is because Fedora 41 moved to using Tuned (https://tuned-project.org/) replacing power-profiles-daemon (https://linuxconfig.org/how-to-manage-power-profiles-over-d-bus-with-power-profiles-daemon-on-linux) 

I just updated to Fedora 41, if I run `sudo tuned-adm list` it shows the system is in `balanced` profile. 
If I run a steam game with `gamemoderun %command%` the gamemode system tray icon shows that gamemode is running. 
But while it says it is running the system remains in the `balanced` power profile. 

```
sudo tuned-adm list

Available profiles:
- accelerator-performance     - Throughput performance based tuning with disabled higher latency STOP states
- aws                         - Optimize for aws ec2 instances
- balanced                    - General non-specialized tuned profile
- balanced-battery            - Balanced profile biased towards power savings changes for battery
- desktop                     - Optimize for the desktop use-case
- hpc-compute                 - Optimize for HPC compute workloads
- intel-sst                   - Configure for Intel Speed Select Base Frequency
- latency-performance         - Optimize for deterministic performance at the cost of increased power consumption
- network-latency             - Optimize for deterministic performance at the cost of increased power consumption, focused on low latency network performance
- network-throughput          - Optimize for streaming network throughput, generally only necessary on older CPUs or 40G+ networks
- optimize-serial-console     - Optimize for serial console use.
- powersave                   - Optimize for low power consumption
- throughput-performance      - Broadly applicable tuning that provides excellent performance across a variety of common server workloads
- virtual-guest               - Optimize for running inside a virtual guest
- virtual-host                - Optimize for running KVM guests
Current active profile: balanced
```
