### ISSUE TITLE
Missing a sysv init script

### ISSUE THREAD

**Issue by NotMrFlibble** [FeralInteractive/gamemode#51]
Not all of us use systemd…

**Comment by chewi** [comment]
It's not that simple, the service itself actually requires systemd though it could be made to work without it. See #15.

**Comment by edddeduck** [comment]
@NotMrFlibble As per @mdiluz comment (see https://github.com/FeralInteractive/gamemode/issues/15) the design has a clear separation, so it's entirely possible for someone to come and program a non-systemd messaging backend that'll still work with all the same client code. 

If you or someone else write one we'll happily test and merge a PR that has this functionality but given the resources available and the smaller number of people requesting it we don't have any plans to write one in the immediate future.

**Comment by esmithferal** [comment]
@NotMrFlibble As per @mdiluz comment (see https://github.com/FeralInteractive/gamemode/issues/15) the design has a clear separation, so it's entirely possible for someone to come and program a non-systemd messaging backend that'll still work with all the same client code.

If you or someone else write one we'll happily test and merge a PR that has this functionality but given the resources available and the smaller number of people requesting it we don't have any plans to write one in the immediate future.
