### ISSUE TITLE
Gamemode with Wine

### ISSUE THREAD

**Issue by gabrieldnzs** [FeralInteractive/gamemode#53]
Hi, sorry if this is the wrong place to ask, i'm new to linux. Is there a way to start gamemode for a game tha runs on steam installed on Wine?

**Comment by MarechalLima** [comment]
You can add `LD_PRELOAD=/usr/\$LIB/libgamemodeauto.so` on Exec line in a .desktop, or if you are using Lutris, you can just insert on Environment variables : 
![image](https://user-images.githubusercontent.com/10439087/40079252-a1a2293e-585d-11e8-96ec-86f7da19e811.png)

**Comment by gabrieldnzs** [comment]
@MarechalLima It worked with Lutris! Thanks, i didn't know about it. :+1:
