### ISSUE TITLE
Enabling Systemd unit makes CPU stay in Performance mode

### ISSUE THREAD

**Issue by Vthyarilops** [FeralInteractive/gamemode#54]
The title pretty much sums it up, normally my CPU is in powersave, but if I enable the systemd unit my PC is stuck in performance mode all the time I am unsure if this is the intended behavior. Also if I preload libgamemodeauto.so the governor stays in performance mode after I close the program (it keeps gamemoded -l running). Is there any way that I can make gamemode default to powersave, change to performance when I preload the library, then revert back to powersave after? 

Also just realized if I load a game that preloads libgamemodeauto.so (which keeps gamemoded -l running) I can't open any other games that preloads libgamemodeauto.so unless I stop the service which results in the terminal hanging and gamemoded staying open, anyways sorry if this is the way it is suppose to function.

**Comment by mdiluz** [comment]
This sounds like a bug.

What version of gamemode are you using?

What's the output of systemctl --user status gamemoded at various steps of your description?

**Comment by Vthyarilops** [comment]
Linux Mint 18.1, Gamemode 1.1. 

PC is loading the module even after systemctl --user disable gamemoded.service so I have to kill it to revert to powersave after I boot

output after I boot

~ >>> systemctl --user status gamemoded                                        
● gamemoded.service - gamemoded
   Loaded: loaded (/etc/systemd/user/gamemoded.service; disabled; vendor preset:
   Active: inactive (dead)

I will test in a moment and update my comment

**Comment by Vthyarilops** [comment]
Well I made a bash script that contains "sleep 5 && systemctl --user stop gamemoded && sleep 2 && systemctl --user start gamemoded" I have it start with the pc with the service enabled, it seems to fix it most times I boot, otherwise I have to disable the re enable the service then stop/start it. So sort of fixed, finding the root of this problem would be nice.

**Comment by Vthyarilops** [comment]
Fixed in 1.2, thanks Feral and everyone who contributed to this project, really helps DXVK games.
