### ISSUE TITLE
Uninstall documented?

### ISSUE THREAD

**Issue by cdplayer** [FeralInteractive/gamemode#59]
There is no clear instruction that i've seen to disable and/or fully remove this software.

If the code was made available as PPA it could be more easily updated/autoupdated/removed. Adoption of this might increase too perhaps.

Having had issue with my system after install I had hope to cleanly remove this for diagnosing, and have hardware configuration return to default state.

**Comment by fuckyourselfup** [comment]
You could remove manually the files after you have disabled gamemoded.service.

**Comment by mrintrepide** [comment]
```
$ systemctl --user disable gamemoded.service
# rm /usr/lib64/libgamemode.so /usr/lib64/libgamemodeauto.so /usr/bin/gamemoded /usr/libexec/cpugovctl /usr/include/gamemode_client.h /usr/share/man/man1/gamemoded.1.gz /etc/systemd/user/gamemoded.service /usr/share/polkit-1/actions/com.feralinteractive.GameMode.policy
```

**Comment by aejsmith** [comment]
You can run `ninja uninstall` from the build directory, after stopping the service with systemctl if it is currently running.

I'll add some notes to the README.
