### ISSUE TITLE
ini file in /usr ?

### ISSUE THREAD

**Issue by lemmy04** [FeralInteractive/gamemode#6]
is there any reason why the configuration file is not in /etc?

**Comment by mdiluz** [comment]
By my understanding, `/etc` is typically for OS/distribution configuration files, and `/usr` is for installed programs.

Perhaps that's incorrect however, so the debate floor is open :)

**Comment by ikeydoherty** [comment]
Distribution packaging and vendor defaults come to mind. In `/etc` would lead to merge conflicts on update between user changes and local changes. A more robust approach could be the stateless cascade:

`XDG_CONFIG_HOME`
`/etc/`
`/usr/share`

In terms of **shipped default data** - it should be in `/usr/share`

**Comment by lemmy04** [comment]
...with XDG_CONFIG_HOME being ~/.config ? that would do. quite nicely.

**Comment by ikeydoherty** [comment]
XDG_CONFIG_HOME falls back to `$HOME/.config` in the absence of the `$XDG_CONFIG_HOME` variable being set. I put some helpers into LSI for getting the correct variant:

https://github.com/solus-project/linux-steam-integration/blob/master/src/common/files.c#L53

I could relicense them by way of PR to the codebase and implement the cascade if thats something that @mdiluz wants. The question then becomes is it an exclusive-or config approach or a merge and overwrite? :)

**Comment by mdiluz** [comment]
I'd accept a PR for that, and a merge-overwrite approach might be best. Even some way to merge without the overwrite would be useful if it doesn't make things too complicated.

**Comment by ikeydoherty** [comment]
Alright so I'll look to get a PR in tomorrow as we're approaching EOD here and I could murder a sandwich.

**Comment by lemmy04** [comment]
if i was writing this I would do it like this:

1. read /usr/share/gamemode/gamemode.ini
2. read /etc/gamemode.ini, keep defaults from 1) if unset in 2)
3. read ~/.config/gamemode.ini, keep existing values from the merge of 1) and 2) if unset in 3)

**Comment by ikeydoherty** [comment]
Well we could take a map approach and don't clobber away existing keys, just update the values in a merge. Pretty trivial.

**Comment by tpruzina** [comment]
This should definitely load .config from $HOME, if that doesn't exist fallback to etc/usr.

**Comment by mdiluz** [comment]
@ikeydoherty I've marked a 1.1RC given the amount of other nice chances in, did you make an progress on this one?

**Comment by mdiluz** [comment]
I've implemented this as part of 1.1RC in 8bd9587e80a0fb9b
