### ISSUE TITLE
Fedora package related issues (lib versioning)

### ISSUE THREAD

**Issue by gicmo** [FeralInteractive/gamemode#61]
Hi,
I work in Red Hat's Desktop Hardware Enablement team and are currently working on packaging gamemode for Fedora (see [fedora-workstation issue 61](https://pagure.io/fedora-workstation/issue/61), review request [rhbz#1596293](https://bugzilla.redhat.com/show_bug.cgi?id=1596293)).
After doing the initial packaging I have a couple of questions/issues:

* Issues:
    - [ ] location of the libraries (currently `/usr/lib64`)
  They are unversioned which normally is a big no-no: "In cases where upstream ships unversioned .so library (so this is not needed for plugins, drivers, etc.), the packager MUST try to convince upstream to start versioning it."  ([see "Downstream .so name versioning"](https://fedoraproject.org/wiki/Packaging:Guidelines#Shared_Libraries)). Maybe that is ok to not have them versioned, because they are internal, i.e. get dlopen'ed by the inlined functions from the inlined functions in the header, but then we should install them in a private location (i.e. `/usr/lib64/gamemode/` like we did for renderdoc). OTOH, umockdev also has a private, ld-preload only library and that is versioned: `/usr/lib64/libumockdev-preload.so.0` & `libumockdev-preload.so.0.0.0`.

* Questions:
    - [ ] location of the gamemoded daemon (currently `/usr/bin`)
  Any reason why it is not in `/usr/libexec/`?

    - [ ] man page section for `gamemoded` (1 vs 8)
  It is a daemon, so should be in section 8?

More out of curiosity, why a session daemon and not a system one?

**Comment by aejsmith** [comment]
Thanks for working on packaging this. I've merged your pull request.

I don't think there's any particular reason for /usr/bin vs /usr/libexec. Is Fedora's preferred location for daemons /usr/libexec?

You're right on the man page section. I'll move it.

There's a couple of reasons for using a session daemon:
- Means that the whole daemon doesn't run with elevated privileges, just the parts that need it (cpugovctl).
- Allows configuration on a per-user basis - one of the locations it attempts to read the configuration from is the the user's home directory.

**Comment by gicmo** [comment]
Thanks for the quick review of the patches!

I think some people prefer `libexec` for programs that are not directly run by the user, as mentioned in the [libexec section](https://fedoraproject.org/wiki/Packaging:Guidelines#Libexecdir) of the Packaging Guidelines. OTOH there are session daemons (started by systemd) that are located in `/usr/bin`, e.g. pipewire, pulseaudio, rdm. So I guess we could just leave gamemoded where it is! Unless something else comes up, I think we are good w.r.t. to Fedora. ;)

Also thanks for the clarification about the session daemon. The per-user basis config makes a lot of sense to me. I was initially thinking what would happen when we have two logged in users with two "competing" daemons, but I guess that is a far fetched and theoretical case. ;)

**Comment by aejsmith** [comment]
OK, yeah, I'll leave it in `/usr/bin`. There is actually some use to having it there - running `gamemoded -r` will send a request, wait for a signal then exit, which can be used to manually enable game mode rather than having to preload the library into some other app.

I see you've added all the changes as patches in the package, but I'll aim to do a new release sometime next week as well.

**Comment by gicmo** [comment]
I have submitted the package to Fedora [rawhide](https://koji.fedoraproject.org/koji/taskinfo?taskID=28050381) and also an update for [F28](https://bodhi.fedoraproject.org/updates/FEDORA-2018-dab8a21270). A new release would be highly appreciated though! Thanks a bunch!

**Comment by aejsmith** [comment]
Apologies for taking a while to get around to it, but 1.2 is now released.
