### ISSUE TITLE
No such file or directory: ".../build

### ISSUE THREAD

**Issue by Prime624** [FeralInteractive/gamemode#65]
**Describe the bug**
Upon following the directions to install, I get a fatal error when trying to run bootstrap.sh.

**To Reproduce**
Steps used to reproduce the behavior:
1. Install meson and other packages listed on the readme.
2. Run git commands listed under directions for either 1.1 or the master branch.
3. ./bootstrap.sh from within `~/gamemode`
4. Receive this error:
```
+ meson --prefix=/usr build -Dwith-systemd-user-unit-dir=/etc/systemd/user
Error during basic setup:

[Errno 2] No such file or directory: '/home/brexton/gamemode/build'
```

**Expected behavior**
The bootstrap.sh would run without errors and gamemode would have successfully been installed.

**System Info (please complete the following information):**
 - OS and version: Ubuntu 16.04
 - GameMode Version: both master and 1.1

Edit: Apparently this can be solved just by creating a build directory before running bootstrap.sh. This should probably be added to the instructions.

**Comment by m-svo** [comment]
What are the versions of ninja-build and meson currently on your system?

**Comment by Prime624** [comment]
Ended up just being the folder not created. However that should be added to the instructions.

I additionally had another error later with meson being too low a version, but was able to update it and finish the install.

**Comment by m-svo** [comment]
> Ended up just being the folder not created.  
I had the same issue, it's due to meson version too low. build is created okay with the right version.

**Comment by aejsmith** [comment]
See #22 - newer Meson automatically creates the build directory, and we also currently need a newer version for other reasons as well.
