### ISSUE TITLE
DEB packages in each release, not just source

### ISSUE THREAD

**Issue by BloodyIron** [FeralInteractive/gamemode#70]
Any chance we can get DEB packages built for each release of this? (latest + going forward?).

Compiling the source for install means that package managers can't manage things like updates, or removal. Additionally, having it as a source only option makes it less accessible to new Linux users, vs a DEB.

Also, if we could get the DEB to setup any PPA repo that's available for such that'd be great, so users get updates without having to manually add a repo (but I dunno if a PPA even exists yet).

**Comment by fuckyourselfup** [comment]
Please read [this link](https://github.com/FeralInteractive/gamemode/issues/58#issuecomment-403272417).

**Comment by BloodyIron** [comment]
Any chance we can get that added to the docs then?

**Comment by aejsmith** [comment]
There are now Ubuntu and Debian packages available in the official repositories.

**Comment by BloodyIron** [comment]
Awesome! Thanks! :DDD
