### ISSUE TITLE
Gamemode, Flatpak and PID tracking

### ISSUE THREAD

**Issue by nanonyme** [FeralInteractive/gamemode#73]
Greetings,
We noticed while implementing https://github.com/flathub/com.valvesoftware.Steam/issues/77 that gamemode relies for many of its capabilities on PID tracking. As it may not be possible for a client running under Flatpak to know its real PID due to PID namespacing being used, do you see it possible for any part of gamemode to function in such an environment?

**Comment by nanonyme** [comment]
Note that a more reliable way to get PID to track for termination might be to ask Dbus but that wouldn't help if you want to nice processes

**Comment by kakra** [comment]
Maybe GameMode should just be integrated into the flatpak? It should solve the problem but it may need adjustments now to allow changing governors etc.

**Comment by kakra** [comment]
We could probably use `SCM_CREDENTIALS` and `sendmsg()`/`recvmsg()` to translate the PIDs but that requires a shared unix socket. I'm not sure how to do this without an incompatible change to the dbus interface. Maybe @aejsmith  or someone else from Feral could shed light on this?

**Comment by aejsmith** [comment]
Sorry for the slow response, this went under my radar while I was on holiday.

You're right that GameMode does rely on knowing the PID of the clients. The renicing/scheduling policy behaviour is optional, but outside of that it also attempts to track the PID to know when the client has terminated.

I don't really have much knowledge of the details of how Flatpak works, so just to clarify - are all processes running under Flatpak visible to processes outside of the sandbox, just with a different PID to what they are seen as inside the sandbox?

Do you know if getting the PID of the client from D-Bus would be reliable? If not, I saw a suggestion on the Flathub issue of running a service inside the sandbox which implements the GameMode D-Bus API, handles PID translation, and passes that to the real service outside the sandbox. That seems like a reasonable approach to me.

**Comment by nanonyme** [comment]
PID of the client is reliable only in the sense that when entire application with all its processes terminates, dbus-proxy will terminate. So you may or may not be following lifecycle of the process that requested gamemode

It might be that a gamemode Flatpak Portal (essentially means some proxy services and doing translating for regular gamemode) would be better in the long run anyway as it involves concepts like asking user consent before turning gamemode on. If I understood correctly, this is what the suggestion was about

**Comment by gicmo** [comment]
Support for GameMode, via the new GameMode portal, was added back to the steam flatpak (beta) with PR flathub/com.valvesoftware.Steam#384, so I think this can be closed.
