### ISSUE TITLE
Automatically disable compositing window managers

### ISSUE THREAD

**Issue by ganthore** [FeralInteractive/gamemode#88]
**Is your feature request related to a problem? Please describe.**
Should gamemode be able to interact with window managers in order to suspend/stop compositing?

**Describe the solution you'd like**
Perhaps gamemode should check to see if any of the common compositing window managers are running and temporarily suspend/stop them until the game is closed out. Perhaps make this an option toggle in a config file in case some users would rather leave such a feature off.

**Describe alternatives you've considered**
Manually defining kwin rules. It's not pretty but it works for now.

**Additional context**
N/A

**Comment by ibrokemypie** [comment]
it would be great to kill and restart compton for example when games start/stop. 
Compton can cause a lot of issues with performance in some games, especially wine games

**Comment by mdiluz** [comment]
For what it's worth, this had been on my backlog for a while, but upon investigation, it's generally the consensus that the window manager itself should be getting out of the way, and work on that is always on-going.

In general, I'd also be worried that messing with the compositor could be a can of worms in terms of causing horrible bugs, especially for users when they alt-tab out and such.

**Comment by aejsmith** [comment]
Per the above comments, I'm going to close this.

> Most SDL games also use this WM hint, so most Linux native games should work. Not sure about Feral game ports, tho... ;-)

All Feral games should set this since we use SDL, and as far as I can tell we've always used a SDL version that supports it.
