### ISSUE TITLE
Liquorix kernel

### ISSUE THREAD

**Issue by lordgault** [FeralInteractive/gamemode#89]
Hello, everybody. More than in problem I have a doubt. Can I use GameMode with the [Liquorix kernel?](https://liquorix.net/) Thank you, greetings

**Comment by mdiluz** [comment]
Probably too late to reply - but I don't see why not. The CPU governer controls may not work, but the other features should.

**Comment by lordgault** [comment]
Thanks anyway for answering.

**Comment by kakra** [comment]
@lordgault This may be a problem if you're using the MuQSS feature:
> `ISO task max realtime use......:  70 %  ->  25 %`

It basically violates the assumptions that are built into the heuristics of GameMode. The problems you may observe are outlined in the README, it also explains where you could reset that value to default.

It's not obvious to me why that kernel changes this value, almost no software actively uses `SCHED_ISO`, it doesn't make sense. As long as there is no `SCHED_ISO` process, it won't steal any CPU resources. Changing this to such a low value may expose you to the kernel flipping scheduling behavior of a game under GameMode every five seconds. You would probably clearly see that during playing... Unless you have a lot of cores (a 24 core system could run 6 cores constantly with `SCHED_ISO` with this setting which is about the same number of cores as 70% for an 8-core CPU, if any more cores start running `SCHED_ISO` processes for more than 5 seconds, MuQSS will fall back to normal scheduling to not starve the system of resources, but 25%/8-core can easily hit this as games constantly fully utilize more than 2 cores).

Let me know if you experience any difference with either value.

**Comment by Batcastle** [comment]
I am running the 4.20 Liquorix kernel right now, have installed Feral Game Mode a number of times and have had no issues. You should be fine.

**Comment by 7ovo7** [comment]
> I am running the 4.20 Liquorix kernel right now, have installed Feral Game Mode a number of times and have had no issues. You should be fine.

have tried any form of beckmark in gaming? Liquorix are better more the default Kernel?

**Comment by Batcastle** [comment]
@7ovo7 Yes, Liquorix is better than generic kernel for gaming. Depending on the game, you could get more stable frame rates, higher frame rates, decreased screen tearing a micro-stuttering, or some combination of all these, depending on the game and the distro. It's especially helpful for games in emulators and/or WINE/POL/Proton. All this (and more) is why the gaming distro [Drauger OS](https://draugeros.org) uses the Liquorix kernel.

If you want actual numbers and benchmarks, I suggest doing them yourself because if you do you can actually experience the differences and see if it is a good fit for you. That, and i always say not to simply take someone's word for it, do you're own research and make your own decisions.

**Comment by 7ovo7** [comment]
> @7ovo7 Yes, Liquorix is better than generic kernel for gaming. Depending on the game, you could get more stable frame rates, higher frame rates, decreased screen tearing a micro-stuttering, or some combination of all these, depending on the game and the distro. It's especially helpful for games in emulators and/or WINE/POL/Proton. All this (and more) is why the gaming distro [Drauger OS](https://draugeros.org) uses the Liquorix kernel.
> 
> If you want actual numbers and benchmarks, I suggest doing them yourself because if you do you can actually experience the differences and see if it is a good fit for you. That, and i always say not to simply take someone's word for it, do you're own research and make your own decisions.

I understand, the variables are so vast, that it is unlikely that something good in one situation may be the same for another. I thank you for this answer.

**Comment by nipnipj** [comment]
Gamemode work fine with default kernel in Archlinux., but Liquorix kernel doesn't allow CPU governor setting. Is this normal?

**Comment by damentz** [comment]
Gamemode works fine on Liquorix:
```
$ uname -a
Linux damentz64 6.9.10-lqx1-1-lqx #1 ZEN SMP PREEMPT Thu, 18 Jul 2024 17:38:52 +0000 x86_64 GNU/Linux

$ gamemoded -t
: Loading config
Loading config file [/etc/gamemode.ini]
: Running tests

:: Basic client tests
:: Passed

:: Dual client tests
gamemode request succeeded and is active
Quitting by request...
:: Passed

:: Gamemoderun and reaper thread tests
...Waiting for child to quit...
...Waiting for reaper thread (reaper_frequency set to 5 seconds)...
:: Passed

:: Supervisor tests
:: Passed

:: Feature tests
::: Verifying CPU governor setting
::: Passed
::: Verifying Scripts
::: Passed (no scripts configured to run)
::: Verifying GPU Optimisations
::: Passed
::: Verifying renice
::: Passed
::: Verifying ioprio
::: Passed
:: Passed

: All Tests Passed!
```

Here's my config:
```
$ grep -P '^[a-z]' /etc/gamemode.ini 
reaper_freq=5
desiredgov=performance
defaultgov=ondemand
softrealtime=off
renice=19
ioprio=0
inhibit_screensaver=1
disable_splitlock=1
apply_gpu_optimisations=accept-responsibility
gpu_device=0
amd_performance_level=high
```
