### ISSUE TITLE
Ubuntu 16.04 build fails

### ISSUE THREAD

**Issue by demonGeek** [FeralInteractive/gamemode#9]
Ubuntu 16.04.4 LTS, followed the instructions and got the following after running `./bootstrap.sh`:

>[Errno 2] No such file or directory: '/home/bob/Downloads/gamemode/build'

Created the `build` directory manually and tried again:

> Native c compiler: cc (gcc 5.4.0-6ubuntu1)
>
>Meson encountered an error in file meson.build, line 32, column 0:
>Unknown function "join_paths".

FYI: meson version 0.29.0.

**Comment by alexbrrsclnt** [comment]
Same problem

**Comment by brunotix** [comment]
Use meson in ppa launchpad.

**Comment by brunotix** [comment]
sudo add-apt-repository ppa:jonathonf/meson
sudo apt update ; sudo apt dist-upgrade

**Comment by demonGeek** [comment]
Thanks @brunotix, that gets me further but I still have problems:

> Enable and run the daemon? [Yy] y
>+ systemctl --user daemon-reload
>Failed to connect to bus: No such file or directory

For the record, here's what I've done so far:

1. Followed the instructions in the readme.
2. Uninstalled the version of meson that ships with 16.04: 
`sudo apt remove --purge  meson`
3. Installed latest launchpad version of meson:
`sudo add-apt-repository ppa:jonathonf/meson`
`sudo apt update ; sudo apt dist-upgrade`
`sudo apt install meson`
4. Re-run `./bootstrap.sh`: received error message above.

**Comment by brunotix** [comment]
@demonGeek try restart operational system

**Comment by demonGeek** [comment]
Tried that, no change - still not working.

**Comment by brunotix** [comment]
@demonGeek I used apt-get install dbus-user-session 
Remove the diretory and re-install with git clone https://github.com/FeralInteractive/gamemode.git
Restart

**Comment by demonGeek** [comment]
Thanks @brunotix but I'm not taking this any further right now. Installing dbus-user-session started causing all sorts of weird issues for me - like Chrome refusing to start.

I think I'll wait until this thing is a bit more stable and just switch the CPU governor mode manually.
